### ISSUE TITLE
Psikyo game

### ISSUE THREAD

**Issue by Laddyacris** [libretro/fbalpha#100]
Hello 
I have a raspberry pi with fba libretro 0.2.97.37 or 0.2.97.38 and retroarch 1.3.6 or 1.3.4
psikyo game work very fine with fba libretro 0.2.9.34 but with fba 0.2.97.37 and higher , 
I have bug sounds, and a catastrophic frame rate.

Only Striker 1945 work fine.

Bug games : 
Battle K-Road
Daraku Tensi
The Fallen Angel
Dragon Blaze
Gunbarich
Gunbird
Gunbird 2
Lode Runner
The Dig Fight (Double écrans)
Samurai Aces
Sol Divide
The Sword of Darkness
Space Bomber
Striker 1945 II
Striker 1945 III
Tengai

Why ?

**Comment by barbudreadmon** [comment]
What's your raspberry pi ? 1 ? 2 ? 3 ?
Also, what distro are you using ? retropie (from my experience and a few issues reported here, speed is horrible on retropie) ? recalbox ? another ?
Last few things i don't understand : those games are slow ? are crashing ? have glitches ? and what do you mean with "Tengai (FBA 0.2.97.30)" ? And what do you mean by  "fba libretro 0.2.9.34" ? fbalpha2012 ? Be precise if you seek help please.

**Comment by Laddyacris** [comment]
Hello @barbudreadmon 
sorry for my english , I am French.

with raspberry 2 on recalbox OS 4.x and raspberry 3 with recalbox 4.1.

glitches like with with fba libretro core like this post on forum : http://libretro.com/forums/showthread.php?t=6555&highlight=psikyo
tengai works well on fba 0.2.97.30 core.

the others are big problem, audio bug and slow.

**Comment by barbudreadmon** [comment]
> glitches like with with fba libretro core like this post on forum : http://libretro.com/forums/showthread.php?t=6555&highlight=psikyo

I know about those glitches, they got solved 2 months ago with https://github.com/libretro/fbalpha/commit/8e3768c7bde9f60baefd4b3697ebc6d9e0b65735 .

Looks to me like some of the games you talk about are related to the https://github.com/libretro/fbalpha/issues/99 issue, which i hope @AkimanBengus will be able to solve

About the speed issues, try with those settings in /boot/config.txt : 
> dtparam=audio=on
dtoverlay=sdhost,overclock_50=84
arm_freq=1350
gpu_freq=550
over_voltage=5
sdram_freq=550
sdram_schmoo=0x02000020
over_voltage_sdram_p=6
over_voltage_sdram_i=4
over_voltage_sdram_c=4
gpu_mem=384

and try running (perhaps recalbox already do this, but do it anyway, without this, your raspberry could downscale your cpu frequency) : 
> echo "performance" | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

before launching a game. Perhaps it'll still won't run at full speed (fba is not targeted at arm@1.35Ghz, so it's a normal thing), i intend to try finding a few speedhacks when i got time to spare, but right now i'm more concerned with crashes and other real issues like inputs not working.

If you don't know how to do what i told, ask recalbox, not me, i don't know how recalbox deal with those settings, i'm not a recalbox user.

Don't come back before updating your software/config, i have a bad personality and i'm quite pissed off when people report things that got solved 2 months ago.

**Comment by barbudreadmon** [comment]
I added a core option to switch between "fast" and "accurate" mode in SH-2 based games (psikyo, cps3 and some kaneko games). Choosing "fast" mode should fix speed issues in those games by skipping timers, but i can't do anything about the other issues those skipped timers will produce (i know some kaneko games will have sound issues with that hack).

Since your other issues were either duplicates from https://github.com/libretro/fbalpha/issues/99 or already solved, i close.
