### ISSUE TITLE
No-Sound games - buzzing sound

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#100]
While testing games that are flagged as [No Sound], varying hertz of static may be heard.

**Comment by dinkc64** [comment]
Hi, can you please give me 2 examples?

**Comment by arnoldsecret** [comment]
dorachan's the loudest of them all, at least what I have tested so far.

**Comment by dinkc64** [comment]
After malloc(), please memset it to 0 like:
memset(buf, 0, nAudSegLen<<2 * sizeof(int16_t));
