### ISSUE TITLE
Rework mappings in fbalpha ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/fbalpha#101]
I think we should rework mappings in fbalpha.

What we are doing right now seems quite far from what fbalpha standalone is doing. Seems to me like fbalpha standalone use lines 188-266 of src/burner/gami.cpp to define its mapping, which seems easier to maintain.

So i'm wondering if there is good reason why we use the current init_bind_map function, is there some obscure limitation in libretro api that prevents us to do things like upstream ? Any idea ? Perhaps @AkimanBengus who rewrote part of this code ? Or @twinaphex who probably wrote an heavy part of the initial libretro-fba implementation  ?

RIght now, many games are unplayable because of missing/bad inputs, and i don't think we'll ever be safe about that if we keep using the current code, it's too much work, and sometimes there are things i don't even understand, like why "(Cocktail)" controls use "bind_map[PTR_INCR].nCode[1] = 0;" while it seems they are for player 2, and why when i change them to "bind_map[PTR_INCR].nCode[1] = 1;", i can't get them to work.

**Comment by barbudreadmon** [comment]
Right now i'm experimenting with this new init_input function : 
http://pastebin.com/raw/hGFRrHc8

It still needs improvement (i need to implement all those core options we have for mapping), but at least it seems to work as expected (no missing/bad inputs).

**Comment by barbudreadmon** [comment]
Ok, i pushed my work, you can revert to old handling by adding USE_OLD_MAPPING=1 to make (i'll remove that in the future if everything is ok), now i'm waiting for feedback.

**Comment by barbudreadmon** [comment]
I reverted to using old mapping by default for now, new one still needs some improvement. You can test new one by adding USE_NEW_MAPPING=1

**Comment by hizzlekizzle** [comment]
This sounds like a good improvement, IMO. AkimanBengus' code was a huge improvement over our original implementation, which was totally static, but having something that's both dynamic and complete would be a further improvement.

**Comment by barbudreadmon** [comment]
I updated my code, it should be similar to the old one for street fighters and neogeo games, not sure about the other games (i used standalone mapping as reference for those, as an example, they switch A/B/C with X/Y/Z for 6+ buttons games which are not street fighters).

It should be the final version, except if i really messed up something, waiting for some feedback before using this as default.

**Comment by barbudreadmon** [comment]
@hizzlekizzle  : 
Do you know what is the "Control scheme : gamepad|arcade" purpose ? I know it changes some input mapping, but i don't know why. If it is a per player preference (like newgen neogeo mapping, or the l/r remapping), then it should be per player, if it is not a per player preference, then i need to know if it couldn't be handled by retroarch autoconfig + remapping.

**Comment by hizzlekizzle** [comment]
IIRC, the 'gamepad' mode swaps mappings around depending on the game/system to work better on a gamepad, while the 'arcade' mode stays static all the time for people using arcade sticks.

**Comment by barbudreadmon** [comment]
Hmmmm then it would make sense to have it per player ?

**Comment by hizzlekizzle** [comment]
yeah, probably so.

**Comment by barbudreadmon** [comment]
I'll open a new issue with the inputs that are still wrong after the major update.
I close this one.
