### ISSUE TITLE
Currently known input issues

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/fbalpha#102]
- Mahjong games : too many buttons for a retropad
- Colecovision games : too many buttons for a retropad
- Ace Attacker : non working parent ? (same on standalone)
- Fighting Soccer : unknown issue (same on standalone, on parent and all clones)
- G.I. Joe : unknown issue (work on standalone, seems to freeze on libretro)
- Crazy Fight : layout is weird (same on standalone)
- Last Survivor : layout is weird (same on standalone)
- Laser Ghost : work on standalone, need to press "fire 2" on both controllers
- Line of Fire / Bakudan Yarou : work on standalone, need to press "fire 2" on both controllers
- Night Striker : layout is weird (same on standalone)
- Poker Ladies : Mahjong game with less button, perhaps i could handle something, but the layout would definitely be weird
- Razzmatazz : unknown issue (marked as non working on standalone)
- Sonic Blast Man : unknown issue (same on standalone)
- SDI - Strategic Defense Initiative : layout is weird (same on standalone)

**Comment by substring** [comment]
spectral vs generation : if you play in training mode, you can't quit/change character with a combo START + [AB]

**Comment by substring** [comment]
no I'm using start as the 1P start button after inserting coins. My hotkey is a different one. Well, if it works for you, then it may indeed be a problem with my setup

**Comment by barbudreadmon** [comment]
There is an issue with the possible fixes i mentioned for twinstick games : pgi->Input.Switch.nCode appears to be unset, and pgi->nInput seems to be null for the "second stick" controls, so i can't map those.

**Comment by paradadf** [comment]
Ace Attacker still has input issues

**Comment by barbudreadmon** [comment]
Ace Attacker - no button working at all
**- Looks like a non working parent, clone seems to run fine**
Beast Busters - Fire doesn't follow the crosshair
**- Fixed in my next commit**
Bullet - Only coin, start and directions are working (you can't fire)
**- Twinstick, fixed in my next commit**
Chanbara - (double joystick?)
**- Yes, fixed in my next commit**
Crazy Fight - the layout doesn't make sense to me: A - ↓, B - ↑, X - ↗, Y - ↙, R1 - ↖, L1 - ↘
**- This one is really weird, it could have a special mapping, do you have any suggestion on how to map it ?**
Deer Hunting - Fire goes only to the center
**- Fixed in my next commit**
Fighting Soccer - after coin you can't select anything
**- It should be fine (from output, i can see every button are correctly mapped, and they are quite classic), but it isn't, i'll check standalone**
Galaxy Force 2 - weird directions?
**- Analog, fixed in my next commit**
G.I. Joe - Coin works but no other button
**- It should be fine (from output, i can see every button are correctly mapped, and they are quite classic), but it isn't, seems to me like the game is freezing, i'll check standalone**
Hyper Crash - Directions (left-right) not working
**- Analog, fixed in my next commit**

I'll check the other games later.

**Comment by paradadf** [comment]
For Crazy Fight I'd suggest:
Y - ↖ X - ↑ L1 - ↗
B - ↙ A - ↓ R1 - ↘

**Comment by barbudreadmon** [comment]
Taisen Hot Gimmick (series)
**- Use around 20 buttons, can't be mapped to a retropad, is mapped to keyboard on fba standalone, i don't know if there is such a feature in libretro**
Konami GT - Directions not working (steering wheel)
**- Analog, fixed**
Last Survivor - No start button working, rotary joystick
**- Controls are weird, but they were working (there is no start button on this one, start button is actually fire 1, which is left button, rotation is handled by bottom and right buttons)**
Lethal Enforcers - you can only control the crosshair, nothing else
**- Analog, fixed**
Laser Ghost - you can only control the crosshair, nothing else
**- Every input seems to be handled properly, i don't know what's wrong, i'll check standalone**
Line of Fire / Bakudan Yarou - you can only control the crosshair, nothing else
**- Same as Laser Ghost**
Lord of Gun - The shoots go to the center only, no crosshair
**- Analog, fixed**
Mechanized Attack - Fire doesn't follow the crosshair
**- Analog, fixed**
Mahjong Gakuen 2 Gakuen-chou no Fukushuu
**- Use around 20 buttons, can't be mapped to a retropad, is mapped to keyboard on fba standalone, i don't know if there is such a feature in libretro**
Wakakusamonogatari Mahjong Yonshimai
**- Use around 20 buttons, can't be mapped to a retropad, is mapped to keyboard on fba standalone, i don't know if there is such a feature in libretro**
Mahjong Quest
**- Use around 20 buttons, can't be mapped to a retropad, is mapped to keyboard on fba standalone, i don't know if there is such a feature in libretro**
Night Striker - Directions aren't properly working
**- Analog, fixed, could make use of an analog mode option (auto-centering seems bad on this one)**
Operation Wolf - Fire goes only to the center, no crosshair
**- Analog, fixed**
Operation Wolf 3 - Line of fire doesn't follow the crosshair
**- Analog, fixed**
Operation Thunderbolt - Line of fire doesn't follow the crosshair (this game isn't booting anymore!)
**- Analog, fixed, boot for me (your romset is up to date ?)**
Poker Ladies - not all buttons assigned
**- Mahjong game, but this one seems to use less input, perhaps i could handle it**
Ponpoko - no button to jump assigned
**- Issue in standalone code, p1 jump was defined twice, fixed**
Quartet - only coin button working
**- Issue in standalone code, p1 controls were overwritten by p3, p2 by p4, fixed**
Razzmatazz - only coin button working
**- Same as Laser Ghost**
Rail Chase - directions not working
**- Analog, fixed**
Sonic Blast Man - I believe this one needs a punching pad?
**- Same as Laser Ghost**
SDI - Strategic Defense Initiative - needs a trackball?
**- Analog, fixed, but weird (use dpad + left analog)**

**Comment by barbudreadmon** [comment]
I updated first comment with currently known issues

**Comment by barbudreadmon** [comment]
asterix's p2 start button is now binded (upstream bug)

**Comment by paradadf** [comment]
Great! I haven't been able to get the latest version to double-check the games you corrected. And I didn't wanted to keep testing as probably there will be some games positively affected by your fixes. But I'll do it!
Again, thank you very much!

**Comment by barbudreadmon** [comment]
I don't use the stick from P2/P3, i use A/B/X/Y from P1, then i use R1/L1/R2/L2 as fire buttons

**Comment by dankcushions** [comment]
if it's useful, i added a core option to mame2003 to map the right analog stick to the ABXY buttons for twin stick games: https://github.com/libretro/mame2003-libretro/pull/60/files

**Comment by paradadf** [comment]
DonPachi (and clones) exits the game when you press coin button or just wait a little after the CAVE logo disappear.

**Comment by barbudreadmon** [comment]
About colecovision, i heard 2,4,6,8 buttons were actually a second d-pad and 5,7,9,0 a third d-pad, is that true for all games ? If it is, i could probably map those to the analog sticks, and map the 6 remaining to actual buttons (# as start, * as select, the last 4 as A/B/X/Y).

**Comment by paradadf** [comment]
Are you talking about the console? This is how it has been done in recalbox (see mapping at the bottom):
https://github.com/recalbox/recalbox-buildroot/blob/f0dd7b9d3272a971dea75e3dc6db88dfc9828a38/board/recalbox/fsoverlay/recalbox/share_init/roms/colecovision/_readme.txt

**Comment by barbudreadmon** [comment]
This is weird, if what i read about coleco's original controller is true (it uses 3 d-pad : the analog on top of the controller + 2 d-pad mixed in the numeric keyboard), your mapping is a nightmare.

**Comment by barbudreadmon** [comment]
I confirm the issue about donpachi on arm, x86 works fine.

**Comment by paradadf** [comment]
Donpachi was working fine on 0.2.97.37, but without sound.

**Comment by barbudreadmon** [comment]
I backported current libretro implementation to fba 0.2.97.37, donpachi works, so it seems to be an issue in codebase.

**Comment by paradadf** [comment]
I just noticed, Speed Spin has the same issue as DonPachi.

**Comment by barbudreadmon** [comment]
Nice, that means msm6295 sound device is probably the culprit.

**Comment by paradadf** [comment]
Super League has missing inputs (I believe), most noticeable in menu. There is some sort of input lag with that game too.

**Comment by paradadf** [comment]
The clone for Ace Attacker (aceattaca), as you said, appears to be responding to inputs. But it is definitely not playable yet, most likely because of its very exotic input combination.
http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=aceattaca&lang=en

**Comment by barbudreadmon** [comment]
donpachi got fixed, speedspn is actually a different issue (please open a new issue when it's about a crash, even if it seems to be triggered by pressing a button), asterix was playable before https://github.com/libretro/fbalpha/commit/af5f0cbfe57f86bba7e90e37faba9b6d399d3d32 so i assume that's why "p2 start" wasn't mapped upstream.
I'll check those input issues when i have some time, not sure when.

**Comment by jdstorm** [comment]
Steering is not possible in outrun and shangon with iBuffalo SNES controllers after I updated to the new Lakka version. The accelerate and brake buttons switched position if I remember correctly.

**Comment by barbudreadmon** [comment]
You need analog stick to play analog games.

**Comment by jdstorm** [comment]
Not with previous versions. Was this removed intentionally? If so, why?

**Comment by barbudreadmon** [comment]
I fixed the analog inputs 3 months ago, the old hack which emulated analog input from the dpad was in the way, so i removed it.

**Comment by RetroUp** [comment]
In response to #112.

Would handling it the same way as bStreetFighterLayout in gami.cpp be good? If a game contains "p1 left" or "p1 up" then set bDigital.

Or handle the same as "is_neogeo_game" and check for the 7 games that contain both digital and analog?

**Comment by RetroUp** [comment]
Oh, just read your rambo3 comment. So the bStreetFighterLayout method wouldn't work. 

I think that would just leave the "is_neogeo_game" type method. Have special conditions hard coded for SDI and any other similar game.

**Comment by barbudreadmon** [comment]
I tried to handle twinstick games in libretro.cpp (lines 1849-1904) but what i did don't cover all the cases.
Imho, what needs to be done is something similar, but instead of only detecting if up/down/left/right is mapped, it needs to detect if axis is mapped too. First of [up/down/left/right]/[x-axis/y-axis] need to be mapped to both dpad/lstick, second of [up/down/left/right]/[x-axis/y-axis] needs to be mapped to rstick (unlike at the moment where it is mapped to [x/y/a/b]).

**Comment by barbudreadmon** [comment]
Also, since analog and digital inputs are detected separately, and analog is detected before digital, that won't be easy without rewriting a lot of the current code.

**Comment by RetroUp** [comment]
if (drvname && strcmp(drvname, "sdi") == 0)

**Comment by barbudreadmon** [comment]
I want to avoid maintaining a list of special games as much as possible.
The "autodetect from listed inputs" i wrote a few months ago is fine, it is just incomplete.

Also, i want to add some kind of "machine.ini"/"game.ini" customization for inputs and dipswitches (i don't like how current code populate my retroarch-core-options.cfg with hundreds of lines)

**Comment by Tatsuya79** [comment]
P2 inputs not working for backfire.

**Comment by sergiobenrocha2** [comment]
Chase HQ - layout is weird

We should do something like this: https://github.com/libretro/mame2014-libretro/commit/03b57b18f9d59bcf1e43efb867ffd234325594db

Retro button A -- accelarator
Retro button B -- brake
Retro button R -- gear shift
Retro button X -- turbo

I did something similar to Out Run and other race games.

**Comment by sergiobenrocha2** [comment]
Dynasty Wars - layout is weird

See https://github.com/libretro/mame2014-libretro/commit/3d66d17d91500101b82f86cc4507ea51a456db87

Even using arcade scheme you get a weird layout, with A to left attacks and B to right attacks, should we swap it?

**Comment by sergiobenrocha2** [comment]
ddsom and ddtod have L and X swapped in gamepad scheme, shouldn't they have the same layout?

ddtod arcade scheme is OK (it's the same of mame), ddsom arcade scheme should swap X and Y to have the same scheme of ddtod.

**Comment by sergiobenrocha2** [comment]
After Burner II - missing speed control assignment 

It should be:

Speed Up: R
Speed Down: L

**Comment by sergiobenrocha2** [comment]
Golden Axe - weird layout in both gamepad and arcade schemes

Gamepad: shouldn't it be more like dino and others beat 'em up? Like:

Retro button B -- Jump
Retro button Y -- Attack
Retro button X? -- Magic

Right now you have B to Attack, A to Jump and Y to magic, so the button you use often to attach you spend your magic by accident D:

Arcade scheme should reflect what MAME uses:

Retro button B -- Jump
Retro button A -- Attack
Retro button X -- Magic

**Comment by sergiobenrocha2** [comment]
Super Hang ON - bad layout in gamepad scheme

You have the accelerator pedal in the Y, and the super charge in A button, it's quite hard to both in the same time. Shouldn't it be something like this:

B -- Accelerator
Y -- Super charge
A -- Brake

Arcade scheme is fine, it has the same mame behavior

**Comment by vince-geekcore** [comment]
Sunset Riders > Cannot start the game on FBA Alpha v0.2.97.39

I've got 2p & 4p versions of the Sunset Riders rom. Unfortunately i'm unable to insert coin or start the game with 1p or 2p start button. These buttons are configured correctly in the RetroArch input menu (i've separate 1/2 start buttons & coin button). So the Sunset Rider intro shows but i'm unable to go to the character selection screen.
Pressing the configured fire buttons does not help either. It does work on Mame2003 but i would like to run it on FBA. Is this a bug or misconfiguration?

**Comment by barbudreadmon** [comment]
@vince-geekcore you are being way too imprecise : what's the name of your rom ? I see 14 different version of this game in fbalpha's sources. Furthermore, i didn't see any bug in the 3 input "templates" they use, so this is most likely a misconfiguration. If you want my opinion, you messed up your input configuration because you don't use autoconfig, perhaps you should take a look at https://github.com/libretro/fbalpha/issues/121

**Comment by vince-geekcore** [comment]
@barbudreadmon : this was indeed a config issue, Sunset Riders. Turtles in Time, Ninja Warriors start buttons do work. Sorry about that.

**Comment by shakkalakka** [comment]
Super Gem Fighter Minimix
the first 2 Buttons (A/Cross [PS] and B/Circle [PS]) are mapped to Volume (+/-) instead of Arcade-Button #1/#2
The actual Arcade Buttons #1/#2 are mapped to X/Square and Y/Triangel.

**Comment by sergiobenrocha2** [comment]
@shakkalakka you are referencing other issues, use a space between # and 1

**Comment by spielvan** [comment]
This is having a bug with FBA Alpha, with games Out Run arcade from SEGA, the game runs at normal speed, but neither the digital nor the analog works, making it impossible to move sideways, the other buttons work normally, already does a good Time that has this bug.

**Comment by retro-wertz** [comment]
@spielvan - specify on what system you are testing. for all i know, analog for outrun works fine on windows and linux.

**Comment by spielvan** [comment]
@retro-wertz It's in my android tv box MX3-G with android 5.1.1, and I already say that 2 games of CPS1 are not loading with it, Willow and Forgotten Worlds, the same two work, usually with FBA 2012.

And I do not know if you are responsible for the FBA 2012 of nintendo wii, a long time that the game Forgotten Worlds, can not be played, due to not being able to give Start in this game, already comes from retroarch 9.9.8.

**Comment by retro-wertz** [comment]
testing forgottn and willow on fba2012 and fbalpha with android, analog does not work. pc is down so cannot confirm if analog as suppose to work with the game. any specific romset you are using(actual filenames in case of split romsets)

and no, im not directly involved with development. just helping out confirming issues and troubleshooting-push commits if its not so complicated.

**Comment by barbudreadmon** [comment]
I'll try taking a look at all those suggestions in the next few weeks, i already addressed some. The code for fine tuning default controls for specific games is quite easy to write since my last refactoring. Also i intend to remove the "arcade" layout in the long term.

**Comment by barbudreadmon** [comment]
@sergiobenrocha2 
Chase HQ controls in fba are like this : 

> 
	A("Steering"         , BIT_ANALOG_REL, &TaitoAnalogPort0     , "p1 x-axis" ),
	{"Brake"             , BIT_DIGITAL   , TC0220IOCInputPort0 + 5, "p1 fire 1" },
	{"Accelerate"        , BIT_DIGITAL   , TC0220IOCInputPort1 + 5, "p1 fire 2" },
	{"Turbo"             , BIT_DIGITAL   , TC0220IOCInputPort1 + 0, "p1 fire 3" },
	{"Gear"              , BIT_DIGITAL   , TC0220IOCInputPort1 + 4, "p1 fire 4" },

So gear in fba is not an analog control i can split into 2 buttons. 
I'll ask upstream about this, i found some forum topic bissecting the cabinet there : http://www.ukvac.com/forum/taito-chase-hq-fix-tidy-up_topic357660_post994952.html .
It does seem like gear is indeed supposed to be an analog control to me.

Also, i took care of all your suggestions (actually i also ended up tuning dynasty wars controls), feel free to post more.

**Comment by sergiobenrocha2** [comment]
I actually changed Dynasty Wars again, take a look: https://github.com/libretro/mame2014-libretro/commit/7191b41b46582c6441c6003750ad0b081a802448

**Comment by barbudreadmon** [comment]
@sergiobenrocha2 : 
i did the following on dynwar : 
Attack Left => B
Attack Right => A
Special => Y
It makes more sense than my previous layout on arcade stick, and don't change much on joypad.

Also, if anyone got suggestions for mjleague ( @RetroUp ? ), i'm interested, sport games are not my thing, the "Bat swing" didn't seem to have multiple position so i just mapped it to B, i don't know what the other 5 buttons do.

**Comment by barbudreadmon** [comment]
Some updates : 
- I removed the "arcade" scheme (didn't make sense except if you mapped your controller without following the controller to retropad mapping recommandations from libretro, the most harmful part of this is that some people thought it was the recommanded layout if they played on an arcade stick, while it should probably be "modern" for 99.9% of the arcade sticks since the PS1 era)
- I mapped megadrive the same way as other megadrive cores (except Street Fighter 2 where i used the arcade/snes layout).
- I changed hangon/goldenaxe mapping to reflect their megadrive port layout.
- I restrained the neogeo "modern" layout to the kof, fatal fury and samourai showdown series (having 3 buttons games mapped as Y/B/X with this layout felt wrong and kinda harmful)
- I standardized the generic layout (in most cases, it makes more sense if buttons are mapped as B/A/Y/X/R/L/R2/L2 following their button number, the exceptions should be handled separately)
- I mapped MSX controls (button 1 = B, button 2 = A, Key F1 = start, Key F2 = select, Key F3 = Y, Key F4 = X, Key F5 = R, Key F6 = L, Key UP/DOWN/LEFT/RIGHT = right analog)
- I dealt with @sergiobenrocha2 and @RetroUp recommandations (for various reasons, i didn't follow all of them though), next are @paradadf 's.

Let me know if there is anything weird with those changes

**Comment by shakkalakka** [comment]
i have several arcade sticks and fightpads in use. for that divice the arcade controll schemes work very well, if you remove this i stick with the outdated versions of fba.

**Comment by fr500** [comment]
He already did and I agree, it's the right thing to do.

**Comment by shakkalakka** [comment]
i think the bigges loss is creating a new input scheme for arcade games for gamepads only in mind :P

**Comment by fr500** [comment]
RetroArch simply doesn't accomodate for arcade sticks.
As long as you bind your devices following retropad convention it's no big deal.

**Comment by shakkalakka** [comment]
if i rebind the arcade device to fit mame/fba-layout they will suck on all other plattforms...

**Comment by barbudreadmon** [comment]
Could you explain your setup ? I have most of those controllers you mention, i use autoconfig, and i have 0 issue with any core with default mappings, except if i'm trying to do something weird like playing mario kart on a fighstick/fightpad (you could with a hori fighting commander though).

The whole purpose of the retropad abstraction layer + autoconfig is to have a somehow standard mapping across any controller, in your case : 

**Madcatz fightpad** 
L1 L2
Y X R1
B A R2

**Madcatz fightstick pro**
Y X R1 L1
B A R2 L2

**Xbox/PS**
L2 R2
L1 R1
Y X
B A

**Snes**
L1 R1
Y X
B A

When a core maintainer write a default controller mapping, he is assuming the final user use one of those (again : that's the whole purpose of having the retropad abstraction layer). If you decide to use something else, that's your personal choice, finding a way to handle your personal decision is not something that should be handled in the core code, it could easily be handled through core remapping though.

I can't see any core which would have any issues with those autoconfig mappings. And in the fba case, the first 2 would fit perfectly with modern, the 3rd would fit with classic and modern depending on your taste, the 4th would fit with classic.

I'll be happy to help you fix your setup if you can explain it to me, and if you are okay with using autoconfig (which is, for someone who have a wide variety of controllers, the best feature of retroarch), but i can't keep a core setting which is misguiding people because of its name, and only making sense if your controllers aren't mapped the way retropad was designed to work.

**Comment by Oggom** [comment]
> i can't keep a core setting which is misguiding people because of its name

And simply renaming it is not an option, apparently.

**Comment by shakkalakka** [comment]
cant explain my "cases" much further then i did (my english is not the best)

**Comment by barbudreadmon** [comment]
@Oggom @shakkalakka  : again, if you are okay with using autoconfig, i'll be happy to help, it will be easy to have all core mappings working perfectly with any controller (both joypad and arcade stick), once you start using that. The only issue that could happen is that your controller is not one of the 150 different models supported by autoconfig, and i would gladly help you adding it to the database (take less than 5 minutes).

**Comment by barbudreadmon** [comment]
Except mahjong, colecovision and some upstream issues (shot not following crosshair in some shooting games), controls in the mentioned games should be fine now, i also did some extra tuning for racing games.
If you find any more issues with controls, let me know.

Next step would be to move macro/autofire/diag/service controls from core options to controls.
@fr500 any good news about the "dummy" input descriptor ?

**Comment by sergiobenrocha2** [comment]
After Burner II was used to be like this:

Y - shot/vulcan
B - missile

Starting in 89373db, it's now:

A - missile
B - shot/vulcan

Is it right? Using Classic

**Comment by barbudreadmon** [comment]
Prior to this commit, we would use 3 different default button assignment order for any game which wasn't a 6-buttons versus fighting one, depending on hardware and total number. I removed that and used only the B/A/Y/X/R/L/R2/L2 (B/A/Y/X/R/R2/L/L2 with modern) order for general use. There are a few reasons for this, you can read about those here : https://github.com/libretro/mame2003-libretro/pull/123 .

We can discuss about adding a special case for 2 buttons games if you think the new mapping have a major issue for those (honestly i never really understood why neogeo 2 buttons games would use B/A while non neogeo 2 buttons games would use Y/B, i just inherited this choice from previous implementation when i tried to refactor the mapping system).

**Comment by sergiobenrocha2** [comment]
So you change mame2003 from Y/B to B/A right, I tested here. But mame2003 and fbalpha should follow the other mame cores regarding these 2 buttons games:

```
dino:
 fbalpha: attack B, jump A
 mame2003-patch-1: attack B, jump A
 
 mame2014: attack A, jump B
 mame: attack A, jump B

aburner2:
 fbalpha: shot B, missile A
 mame2003-patch-1: shot B, missile A
 
 mame: shot A, missile B
 mame2014: shot A, missile B
```

A special case to swap to B/Y should be nice, perform combo buttons B+Y is easier in this mapping

**Comment by sergiobenrocha2** [comment]
outrun gear should be assigned to R I think, like other race games (change gear: L & R)

shangon should follow other arcade race games, not the sega genesis port

same for goldnaxe, it should follow other beat 'em ups, not genesis port

**Comment by barbudreadmon** [comment]
See this mapping : 
`Y L R`
`A B X`
?
This is what some people ended up with for their controller after disabling retroarch's autoconfig, mapping it manually, all for the purpose to have a somewhat useable default mapping on recent mame cores. Because, it is obvious after my recent tests on popular games, recent mame cores have 0 care for the retropad reference layout and are a total mess with retroarch's autoconfig for so many games (hopefully, there is the osd to remap everything). There is no way i'm using them as mapping reference. Funny thing, from the layout above, you can see A & B are swapped when compared to how a retropad is supposed to be mapped.

I could use the device types to swap B/A to Y/B though.

I'll take a look at shangon and goldnaxe, do you have other 3 buttons racing / beat them up games in mind when you are telling me to follow them ?

**Comment by barbudreadmon** [comment]
@sergiobenrocha2 : I did some search and testing : 
- I confirm i'll stay with the B/A mapping for 2 buttons game, i can't check every original cabinet to see how they mapped those buttons, but from your example (see http://www.gamesdatabase.org/Media/SYSTEM/Arcade//Manual/formated/Cadillacs_and_Dinosaurs_-_1993_-_Capcom.pdf), it seems fbalpha is the one following the orginal cabinet layout. Also, i won't add a device type to switch B/A to B/Y on 2 buttons games, seems kinda overboard for something which is easy to do through normal remapping (remap B to Y).
- I agree with you on outrun
- I agree with you on shangon : all racing games in fbalpha seems to use B to accelerate, A to brake, Y to turbo
- Do you have any example of beat'them'up not using B as attack button ? I mean besides ddsom and ddtod which i forced that way from your suggestion. The ones i tried (ffight, armwar, ssriders) seems to use B to attack, A to jump, Y for special, which is also how ddtod was mapped before i changed it (ddsom had select and special swapped, and i agree it should have the same layout as ddtod). That's how goldnaxe is currently mapped, also the original cabinet used the following mapping which is not that far from what i'm using : 
`--- (magic) ---`
`(Attack) (Jump)`

**Comment by fr500** [comment]
neogeo classic | modern seems broken? 
Both modes work exactly the same for me right now, am I missing something?

CPS2 seems fine

**Comment by fr500** [comment]
kof98 works

**Comment by barbudreadmon** [comment]
@fr500 See line 3929-3944 of libretro.cpp ? The neogeo modern layout only applies to games from the kof/ffury/samsho family, that's a change i did a few months ago since this setting was originaly designed to mimic the layout of those games on modern consoles. Hmmm this is quite weird that garou is not tagged as a kof game, perhaps i should check for HARDWARE_SNK_NEOGEO & GBF_VSFIGHT instead of FBF_KOF | FBF_FATFURY | FBF_SAMSHO

**Comment by fr500** [comment]
Maybe they just forgot.
Adding the flag works, testing for HARDWARE_SNK_NEOGEO & GBF_VSFIGHT doesn't

**Comment by fr500** [comment]
BTW I know some people disagree with the changes but I think the changes are great, offloading stuff to the frontend pushes us to fix our shit too :p

**Comment by barbudreadmon** [comment]
We have a saying in my country : you cannot make an omelette without breaking eggs. Some people had peculiar setup and ended up not liking those changes, but they were needed, and it is a lot easier now to work on mappings.

There is still the macro/autofire stuff to move though :( . Any news about the dummy descriptor ? 
Actually i have been thinking about this : why don't we use something similar to the "RETRO_DEVICE_SUBCLASS" macro ? Let's say instead of using an already defined retropad button, we use "RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 1)" as retro_input_descriptor's id, it would be the first macro button and ends up being 257, with some tweaking retroarch should be able to detect that this 257 is a special case which shouldn't be mapped to anything by default, but should be allowed to be remapped to a valid button ?

**Comment by fr500** [comment]
I tried the dummy button but I failed spectacularly.
Not sure I follow the RETRO_DEVICE_SUBCLASS stuff but I have seen API additions recently that add buttons so what I could try is add a dummy button. And try to swap the columns in the input remapping menu (so it shows all the available physical buttons left, and the bindings right) Then you could have all the extra macros bound to dummy but users could pick any spare button instead.

Still it's a complex thing, what I really want is to add macro support in the frontend in the controls menu. That would solve a lot of issues.

Loosely related, a problem some issues have mentioned recently is that settings modern in a game will result in all games defaulting to modern.

What we can do in that regard is have a different ID for the subclass depending on the system

```
#define RETROPAD_CLASSIC	RETRO_DEVICE_JOYPAD
#define RETROPAD_MODERN_NEO	RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 1) --> for NeoGeo
#define RETROPAD_MODERN_CPS	RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 2) --> for CPS
``

And so forth, but we would need to populate ports with the proper controllers on content which may be complicated.

**Comment by barbudreadmon** [comment]
> What we can do in that regard is have a different ID for the subclass depending on the system

Well, it would just reverse the situation : the people which are currently happy that the modern setting affect all appliable games (basically only fighting games from the neogeo or which have a 3*punch + 3*kick layout) would become unhappy because they would have to select modern setting again every time they switch system. Are you talking about forum topics or about #158 ?

**Comment by fr500** [comment]
IRC conversation mostly.
Guess what we really need to do is to be able to inform the frontend of the system.
Problem is remaps load on content load and this would have to happen a bit later.

**Comment by arnoldsecret** [comment]
Balloon Brothers (ballbros) - coin input doesn't work
Beraboh Man (berabohm) - layout is weird
Blades of Steel (bladestl) - buttons shouldn't be mapped to the shoulder/trigger buttons
Double Dribble (ddribble) - can't move when on offensive, only pass & shoot
Gigandes (gigandes) - coin input doesn't work
Last Striker (kyustrkr) - coin input doesn't work
Mad Planets (mplanets) - can't find a way to rotate ship
Moonwar (moonwar) - can't find a way to rotate ship

**Comment by barbudreadmon** [comment]
@arnoldsecret i have no problem with the coin inputs, do you have coin input mapped to the same button as hotkey or something ? I know sometimes it fails with this kind of setup, never figured out why or how to fix this though, perhaps @fr500 know more about this ?

I'll take a closer look at other input issues when i have some time, probably tomorrow.

**Comment by arnoldsecret** [comment]
@barbudreadmon didn't have the coin input mapped to any button, tested the games on both keyboard and ps4 controller, both don't register a coin input.

**Comment by barbudreadmon** [comment]
> didn't have the coin input mapped to any button

I don't understand, how are you supposed to use coin input if you didn't map it ? Well, anyway those coin inputs are working, so it's most likely an issue with your setup. Check if coin is mapped in your controls (don't know why it wouldn't be though, since it is mapped by default).

**Comment by barbudreadmon** [comment]
@arnoldsecret no idea what could be your issue, it is working perfectly for me on 2 different computers.

**Comment by arnoldsecret** [comment]
that's strange, couldn't coin up on standalone, maybe it's my romset then

**Comment by barbudreadmon** [comment]
@arnoldsecret 

> Beraboh Man (berabohm) - layout is weird

It is now using a sf2-like layout

> Blades of Steel (bladestl) - buttons shouldn't be mapped to the shoulder/trigger buttons

Shoulder/trigger are nicer defaults for twin stick games, i don't intend to change this

> Double Dribble (ddribble) - can't move when on offensive, only pass & shoot

I don't know much about how this game is played, however all inputs are mapped, are you sure it is not normal behavior ?

> Mad Planets (mplanets) - can't find a way to rotate ship

Fixed, now mapped to L/R

> Moonwar (moonwar) - can't find a way to rotate ship

Now mapped to left analog, however it doesn't seem to work.

**Comment by barbudreadmon** [comment]
@arnoldsecret about coin inputs not working, just mentioning this but it seems it is impossible to insert coins in any game if you are pressing several other game keys at the same time. Could it be your issue ?

**Comment by arnoldsecret** [comment]
no. only pressed the LSHIFT key, no other inputs are pressed aside from the coin input button.

**Comment by barbudreadmon** [comment]
@arnoldsecret 
- about ddribble, you have to repeatedly press "button 1" while moving.
- about moonwar, rotation will probably be broken until the next release, however its clone moonwara is now working properly.

Also, you mentioned pressing the LSHIFT key to insert coin, however i see in your screenshot you use the default which is the RSHIFT key.

**Comment by barbudreadmon** [comment]
@arnoldsecret Finally got the rotation in moonwar working too.

One last thing about the coin input issue, i remember seeing reports about people having a similar issue on a few games with coiners, basically it seems the coiner wasn't sending the input for a "long enough" duration (that was something they were able to fix on hardware side), i'm wondering if your setup is not doing something similar because of some obscure windows setting. Since you have the same issue on standalone, you should probably report this on their forum, i'm pretty sure they'll be able to help if this is somehow windows settings related.

Also, i'll close this issue, it was mainly an issue to keep informations centralized when i reworked the controls, filling all future input issues here was not really my objective (and moonwar issue wasn't really related anyway, it was an emulation issue).
