### ISSUE TITLE
gauntlet2p - retroarch crashes when exiting ingame

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#102]
title.

**Comment by dinkc64** [comment]
barbudreadmon, can you please give me a sanitizer log for this game? :)

**Comment by arnoldsecret** [comment]
Exiting on title would normally exit like it should, exiting while ingame (game already on level 1) crashes retroarch.

**Comment by arnoldsecret** [comment]
It seems the problem has fixed itself for some reason.
