### ISSUE TITLE
DAT mismatch or missing sets (console-set)

### ISSUE THREAD

**Issue by LodanZark** [libretro/fbalpha#106]
Some sets are missing or have outdated hashs:

TurboGrafx16:
acrush
advislnd
aeroblst
ballistx
blodwolf
bombman
bombmn93
bravoman
cadash
chasehq
cybrcore
ddungw
deadmoon
deepblue
devlcrsh
dspirit
dungexpl
fantzone
finallap
hitice
jchan
kingcasn
klax
loht
magchase
motoroad
neutopi2
neutopia
nicklaus
ordyne
pacland
parasol
pgolf
raiden
sharrier
sidearms
silentd
soldblad
splatth
sssoldr
svolley
tricky
tvbasket
tvfootbl
tvhockey
veigues
victoryr
vigilant
wbeach

GameGear:
chasehqj 
daisenrg
tamalymp

MasterSystem:
stennisc
termntrb

**Comment by barbudreadmon** [comment]
You mean against MESS ?

**Comment by LodanZark** [comment]
Even having the current dat's green, those set's listed shows as not found through the win32 build:
[FBAlpha_0.2.97.44_Win32_git-7055753.zip](https://github.com/libretro/fbalpha/files/2792259/FBAlpha_0.2.97.44_Win32_git-7055753.zip)

**Comment by dinkc64** [comment]
so basically all games that have a getzipname callback will need the strlen()-4 addition?
eek..

**Comment by barbudreadmon** [comment]
@dinkc64 It works, thanks !
