### ISSUE TITLE
Some samples are not working

### ISSUE THREAD

**Issue by paradadf** [libretro/fbalpha#106]
fireshrk
ghox
mario
vimana

Interestingly, the sample "mario" lets you only hear Mario running, but no other sounds.

**Comment by RetroUp** [comment]
Mario audio doesn't work in FBA. Upstream issue.

The others do work. You probably have older versions of the samples.
Download newest ones from http://www.progettosnaps.net/samples/

**Comment by barbudreadmon** [comment]
Also, fireshark, vimana and tekipaki's roms were finally dumped with audio (see http://caps0ff.blogspot.fr/), so next version of fba won't need the sample for those.

**Comment by paradadf** [comment]
I tried using both samples from the site you posted (both 0.180 and 0.170) and the there was no sound at all. @RetroUp have you tested them?
@barbudreadmon I'm actually surprised that with the latest core changes, I can't even launch those games anymore on my RPi2 (besides Mario).
I think this issue is still valid.

**Comment by paradadf** [comment]
Of course I comverted them to zip files, and my sample path is correct as the other samples work. I don't know what hardware you are using but on a RPi2, this isn't working.

**Comment by barbudreadmon** [comment]
I can't reproduce your issue, those games launch with or without the samples for me, and with the samples i get sound. Could you post some log ? I'm wondering if it could be a ram issue, it seems retroarch use a lot of ram (around 450M, which is 10x ram used for mario, 4x ram used for cps3 games, ...) with those games, so perhaps you should try lowering your gpu_mem.

**Comment by barbudreadmon** [comment]
I can confirm those games use only around 45M of ram when i remove their samples, and i don't think i'll be able to fix a ram limitation issue.
Also, 7z files should load with my latest commit.

**Comment by paradadf** [comment]
Does this log tell you something? http://pastebin.com/8bgDXsRF

**Comment by barbudreadmon** [comment]
There is nothing after that ? Could you post the output of 'dmesg' after trying to launch those games ?
Also, try removing the samples for those games to see if they launch.

**Comment by paradadf** [comment]
There was nothing else after that. 
dmesg output: http://pastebin.com/0WAkyAKi
Removing the samples did allow the games to boot.

**Comment by paradadf** [comment]
Well, thank you! I just tried lowering the gpu_mem_1024  to 448 and fireshrk booted. With gpu_mem_1024=384 allowed me to boot ghox.

**Comment by dankcushions** [comment]
FYI the default 256 mb vram is very sufficient for emulation on the pi, unless you're doing something specialist

**Comment by paradadf** [comment]
@dankcushions vimana doesn't boot (again) if I lower the gpu_mem_1024 to 320, even less with only 256.

**Comment by dankcushions** [comment]
@paradadf samples would only use available system ram, not gpu_mem. i just tried it in FBA with samples and it worked for me with 256 MB gpu mem. it used 82% of my memory though, so definitely could depend on your environment

**Comment by paradadf** [comment]
@dankcushions I use recalbox, so RAM isn't (or shouldn't be) actually a problem. It's not that every sample is causing me problems, but the ones I mentioned. Does vimana works for you (including sound) wirh only 256 mb gpu mem?

**Comment by dankcushions** [comment]
> Does vimana works for you (including sound) wirh only 256 mb gpu mem?

yes

**Comment by RetroUp** [comment]
The files are uncompressed then stored in memory.  The other samples are under 500k. These are over 150mb. That is a big difference.

**Comment by paradadf** [comment]
What I'm quite not understanding is why, being recalbox a lightweight linux distro (and much lighter than retropie), the samples (or to be specific: vimana sample) are not working for me with gpu_mem greater than 360 and lower than 320 (haven't tested 330 to see the exact point). RAM can't be an issue as the sample is working with that modification. I use a RPi2, but the RPi3 has the same amount of RAM.

**Comment by dankcushions** [comment]
the linux part of either distro shouldn't use much memory really. are you using xmb in retroarch? retropie uses rgui. i'm also using a very light emulationstation theme.

well, it works for retropie anyway :)

**Comment by paradadf** [comment]
Nope, my theme is relatively light. Around 50 mb VRAM. And using rgui too.

**Comment by barbudreadmon** [comment]
Is recallbox heavily optimized with -O3 ? (cflags)

**Comment by substring** [comment]
there's a tmpfs on RAM, we don't want to set a tmp partition on a SD

**Comment by barbudreadmon** [comment]
That doesn't help either, so basically part of your ram is used to store your tmp files and you don't have a swap partition for when you need some extra memory.
With those settings, your raspberry won't be able to allocate the 650/700M of memory needed for this game with samples.
Also, my changes from 26/11 and 27/11 didn't help : toaplan samples were disabled before those commits, and increasing samplerate also increased memory consumption.
You'll have to remove the samples for this game and wait for next fba release.

**Comment by paradadf** [comment]
What I don't understand is why, if this should be a RAM problem, the samples do work lowering gpu_mem from 512 (default) to 360.

**Comment by barbudreadmon** [comment]
Your ram for application = 1024 - gpu_mem

**Comment by paradadf** [comment]
Ok, but a gpu_mem from 320 won't boot vimana anymore. And apparently con retropie just 256 are enough 🤔. Any idea why this could be happening?

**Comment by barbudreadmon** [comment]
Actually i'm not sure you understood well : **the higher you gpu_mem, the less ram you have**

**Comment by paradadf** [comment]
I understood your explanation (or I believe so), but according to it lowering the 360-350 gpu mem that works for me to 320 or even less should actually be better in term of available ram. And as I said before, with 320 the game doesn't boot for me anymore. What am I not getting here? Sorry if this is a silly question but I really don't see it.

**Comment by barbudreadmon** [comment]
You mean the game launch when you set gpu_mem at 360, but not when you set it at 320 ? That would be weird indeed.

**Comment by paradadf** [comment]
Yes, that's what I meant.

**Comment by barbudreadmon** [comment]
Hmmm could you give the output of "vcgencmd get_mem gpu" when you set gpu_mem to 360 ? I suspect this is not a valid value, which could cause the gpu_mem to be set at default (which is 64 if i remember well)

**Comment by paradadf** [comment]
I get gpu_mem=360M when it is set to that value, correspondingly for 350 and 320. With just 64 ES doesn't boot.

**Comment by paradadf** [comment]
After having change gpu_freq once on my RPi2, without explanation, gpu_mem_1024=256 allowed me to boot vimana (the most problematic sample for me). There is a gap between 340 and 260 which I can't explain. For the record I post here my results: 
![tests_vimana_fba](https://cloud.githubusercontent.com/assets/15956550/21530114/c7238244-cd3e-11e6-9472-ca65daa4a0bd.png)

Thanks to everyone for the help on solving this issue, which didn't have anything with the core but with my setup.

**Comment by KnightMadeILL** [comment]
Really dumb, n00b question for you. But the upside is, it will be VERY easy to answer: 
When putting the samples into the samples folder in the bios folder, do I unzip them first so the samples folder is a big ol' list of .wav files, or do I put the samples in as .zip s, by game-name?

**Comment by barbudreadmon** [comment]
They need to be zipped.
Also, vimana, fireshrk (and ghox ?) don't need those samples anymore (their spu got dumped a few months ago)

**Comment by KnightMadeILL** [comment]
Thanks!!
