### ISSUE TITLE
FBA not recognising zip files

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/fbalpha#110]
I updated the FBA yesterday and discovered that it not recognise zip files anymore. 
When we choice a game, kof96 for example, is showed the option to open the file how a path or open it with the core. 
What happened?

**Comment by barbudreadmon** [comment]
Not sure i understand (google translate ?), but i'm sure it's either an issue in your rom, your setup, or a change in retroarch behavior. There was no such change in fbalpha-libretro, nothing happened, so i'm closing.
