### ISSUE TITLE
tbowl - erratic inputs reset game

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#111]
title.

**Comment by barbudreadmon** [comment]
What do you mean exactly by "erratic inputs" ? I couldn't reproduce the issue.

**Comment by arnoldsecret** [comment]
try repeatedly tapping the arrow keys.

**Comment by barbudreadmon** [comment]
Ok, by hitting every arrow keys at the same time like a savage on my keyboard for a few seconds while in game, i managed to produce this reset. Seems like an issue in the driver itself, so i'm tagging @dinkc64

**Comment by dinkc64** [comment]
some games crash or do weird things when left+right or up+down are pressed :)  I use a gamepad so I never catch these things.

**Comment by barbudreadmon** [comment]
Thanks, i can't reproduce this issue anymore, closing :)
