### ISSUE TITLE
(Wii U) Bluetooth controllers not detected

### ISSUE THREAD

**Issue by MeisterLLD** [libretro/fbalpha#114]
In the 1.4.0 release, most cores seem to detect bluetooth controllers but FB Alpha 2012 still shows only "Wii U controller #1" in the binding options. The other cores show "Wii U Gamepad #1" / "Wii U Pro Controller #2" / "Wiimote #3" etc.

**Comment by barbudreadmon** [comment]
This is not fbalpha2012's repository, i close.

**Comment by MeisterLLD** [comment]
Oh, sorry, didn't see that. I put it in the proper one.
