### ISSUE TITLE
epr-7391.12 has wrong size [Fantasy Zone (FD1089B 317-0016)]

### ISSUE THREAD

**Issue by LodanZark** [libretro/fbalpha#117]
Current DAT

`<rom name="epr-7391.12" size="8192" crc="c03e155e"/>`

Fixed DAT
`<rom name="epr-7391.12" size="32768" crc="c03e155e"/>`

**Comment by barbudreadmon** [comment]
@dinkc64 actually the size for fantzonee isn't right : https://github.com/libretro/fbalpha/blob/1e1737383a3b1b8ef1837d5dc5cec3359bf5e414/src/burn/drv/sega/d_sys16a.cpp#L1553

fantzonep use the same file with the right length.

Btw, i'm using the same algorythm as standalone to generate dat files, so when the dat file has an error, most likely there is something wrong in the driver.

**Comment by dinkc64** [comment]
oops, I made a mistake thinking it was a diff. file somehow, sorry :)

my excuse: the neogeo cd bugs are driving me bonkers o.O

**Comment by dinkc64** [comment]
yep - loosing my mind :)
