### ISSUE TITLE
Just want to know how activate this

### ISSUE THREAD

**Issue by josecarlosbarros** [libretro/fbalpha#117]
My recalbox is using kind of pifba old emulator I want use fbalpha libretro because its pretty much better. HOw can I do that?

**Comment by barbudreadmon** [comment]
Ask on recalbox's forum, all i can say is that pifba uses really old fbalpha roms, you'll have to find the newest fbalpha roms (0.2.97.39). I'm closing since it is not a fbalpha issue.
