### ISSUE TITLE
Crash when loading rom - iOS

### ISSUE THREAD

**Issue by DarrenBranford** [libretro/fbalpha#118]
HI.

For the last few days, this core has been constantly crashing Retroarch on my iOS devices whenever I try to launch a rom. As I am not having any issues with any other cores that I am using, I was not sure on where to post the issue.

Here is a screenshot of Xcode.

![grab](https://cloud.githubusercontent.com/assets/5956037/22756237/5dd5964e-ee3e-11e6-97ca-9a24690104ab.png)

**Comment by barbudreadmon** [comment]
I don't see why libretro-fbalpha would crash your ios retroarch this last few days : 
- it doesn't crash on other devices
- there was no update to the core for some time (i have been waiting for the 0.2.97.40 release to work on it). 

The code you show is not a part of libretro-fbalpha either (it seems to be part of retroarch), and for obvious reasons (mainly price/performance ratio), i don't own an ios to test, so i don't think it is the right place to ask for help.

**Comment by DarrenBranford** [comment]
Thank you for the reply.

Yes, I was unsure about opening an issue here. I will open a new issue at the Retroarch repo.

I hope that they can help as this is my favourite core!
