### ISSUE TITLE
fbalpha build broken under some gcc instances

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/fbalpha#122]
gcc: error: unrecognized command line option '-fno-tree-loop-vectorize'
gcc: error: unrecognized command line option '-fno-tree-loop-vectorize'
gmake: *** [src/burner/unzip.o] Error 1
gmake: *** Waiting for unfinished jobs....
gmake: *** [src/burn/snd/ym2151.o] Error 1
gcc: error: unrecognized command line option '-fno-tree-loop-vectorize'
gmake: *** [src/burner/ioapi.o] Error 1
gcc: error: unrecognized command line option '-fno-tree-loop-vectorize'
gmake: *** [src/burn/snd/ymf278b.o] Error 1
cp "fbalpha_libretro.so" "/builddir/build/BUILD/libretro-20170303/dist/unix/fbalpha_libretro.so"
cp: cannot stat 'fbalpha_libretro.so': No such file or directory

Suggestions for a work-around are welcome.

**Comment by barbudreadmon** [comment]
You need gcc-4.9. I need to add some gcc detect version feature in the makefile

**Comment by Zombie-Ryushu** [comment]
I have gcc 4.7 on one system, can this be patched to be worked around?

**Comment by barbudreadmon** [comment]
You can edit makefile.libretro and remove "-fno-tree-loop-vectorize" as a workaround.
