### ISSUE TITLE
Macro buttons stopped working

### ISSUE THREAD

**Issue by ji125443** [libretro/fbalpha#124]
As the question ...

**Comment by barbudreadmon** [comment]
No information at all, closing.

**Comment by ji125443** [comment]
Old versions are fine, but new versions don't work.

**Comment by barbudreadmon** [comment]
So, macros stopped working...
Sorry but i don't intend to fix that stuff, mapping macro/autofire in core options was never a good idea, it should be in the frontend realm, not in the core realm.
Maybe @fr500 has some news about macro/autofire support in RA ?

**Comment by ji125443** [comment]
Yes, playing （Neogeo） fighting games is quite important, so hopefully it will be fixed

**Comment by fr500** [comment]
@barbudreadmon I actually brainstormed it the other day, it's totally doable, but it's difficult and I haven't felt to motivated to work in RA lately.

**Comment by barbudreadmon** [comment]
@dinkc64 My main issue with the implementation on core's side is that it's causing issues with netplay if options are different between clients, having it on frontend's side would prevent this issue. I know it's an important feature, that's why i think its implementation in RA should be made a priority, so that all cores can benefit from it.
My second issue with this implementation is that i didn't write it, the code is kinda complex (for a long time now i have wanted to get rid of it), so i'll have a hard time fixing it.

**Comment by furiadeoso** [comment]
I'm agree. Macro must be in frontend side. Core options is actually a problem in netplay. The less, the better.

**Comment by fr500** [comment]
Get rid of it! and open an issue on RA repo regarding input mapper macros :)

**Comment by crazii** [comment]
Not just neogeo, this whole function of fbalpha core is not working. 
I have a habit that uses L/R button for A+B for most beat'em up arcades, now all of them are not working; that still is OK with me. But it is unacceptable when A+B+C is needed in some fighting games and late 90s beat'em up games.

**Comment by barbudreadmon** [comment]
> But it is unacceptable when A+B+C is needed in some fighting games and late 90s beat'em up games.

@crazii It looks totally acceptable to me considering that's how the original hardware was played.
Anyway i explained the plans for this feature and the reasons behind it, so coming just to repeat things we already know and complaining is pretty pointless imho.

**Comment by crazii** [comment]
@barbudreadmon Yes it's acceptable if a arcade stick like the original is used. I had one but lost it on house moving :). But when talking about game pads of all types&sizes, things're kinda different aren't they? I apologize that I just became restless on having this problem. And all the complaining is just hoping it may be get fixed soon. And I totally agree with you about the frontend macro mappers; I gave you a thumb up before my above comments. Its a good design, despite that it may not come that soon. But I can wait.
