### ISSUE TITLE
shufshot - can't shuffle puck

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#125]
seems the trackball for this one needs to be a little more sensitive.

**Comment by dinkc64** [comment]
Hi arnoldsecret,
This one is really unfortunate - I can't get it to work right with a joystick (or kbd).  The game really wants a real trackball for this, to get to speed right.  It will either go too fast, or not at all :(
I can't fix it right now, but I will try to come up with more ideas to try.

best regards,
- dink

**Comment by dinkc64** [comment]
It should be OK now :)
