### ISSUE TITLE
Compilation error on iOS

### ISSUE THREAD

**Issue by twinaphex** [libretro/fbalpha#130]
@barbudreadmon 

This has happened as of today.

This is a log from our buildbot - 

http://p.0bl.net/17115

**Comment by twinaphex** [comment]
I would strongly recommend not using C++11 features if you don't have to, all you are doing by using C++11 features is creating potential portability issues and making it harder to port this code to platforms where there is no C++11 compiler available.

**Comment by barbudreadmon** [comment]
I'm surprised you got an issue only today, those functions have been there for months, perhaps years.

C++11 is used upstream for midway hardware, but this hardware doesn't work in fbalpha-libretro at the moment anyway (and i think it's still WIP upstream)

**Comment by barbudreadmon** [comment]
Just to make sure, the c++98 equivalent would be : 

std::basic_string<char>(dip_option->values_str).swap(dip_option->values_str);

std::basic_string<char>(macro_option->values).swap(macro_option->values);

std::basic_string<char>(macro_option->values_str).swap(macro_option->values_str);

?
