### ISSUE TITLE
Blue palette with konami driver

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/fbalpha#132]
Started with 0.2.97.40, getting a blue palette screen with konami driver (tested dbz2, ssriders, tmnt, tmnt2)

![tmnt-170418-230640](https://cloud.githubusercontent.com/assets/5431285/25160311/bdeaf6cc-248b-11e7-879a-0473d2e8807d.png)

**Comment by barbudreadmon** [comment]
Does the latest commit from @aliaspider fix this ?

**Comment by sergiobenrocha2** [comment]
Nope

**Comment by barbudreadmon** [comment]
My latest commit seems to fix it.

**Comment by sergiobenrocha2** [comment]
Yes, fixed. Thanks!

**Comment by retro-wertz** [comment]
some are fixed, but alot still has blue tint:
twinbee
contra
gradius 1 and 2
battle of atlantis
blades of steel
finalizer
green beret
gyrus
hunted castle
hexion
iron horse
jackal
konamigt
labyrinth runner
mikie
mogura
nemesis
pandoras palace
pooyan
rockin rage
rock n rope
scooter shooter
shaolins road
(etc)

**Comment by barbudreadmon** [comment]
It seems the way we set nBurnBpp in libretro-fbalpha is broken, i'll ask some explanation on how to set it upstream.

**Comment by retro-wertz** [comment]
@barbudreadmon the same condition can be replicated in fba standalone, if we set "video>select_blitter" to "Enhanced" or "Directx9 Alt". this affects these konami games that makes use of KonamiBlendCopy (https://hastebin.com/bupojemijo.css)

**Comment by barbudreadmon** [comment]
Yes i know, dink sent me the fixed konamiic.cpp yesterday, i'll commit it this week-end.

**Comment by retro-wertz** [comment]
this should be ok now...

**Comment by sergiobenrocha2** [comment]
Yeah, it's fixed now, thanks!
