### ISSUE TITLE
Analog input (press up) problem in Night Striker

### ISSUE THREAD

**Issue by litaniast** [libretro/fbalpha#133]
https://www.youtube.com/watch?v=h6JzVYKhuu4
in FB Alpha core. When I stick slide to up(to go down), the player goes down but suddenly go to up to end.

https://www.youtube.com/watch?v=Y9jodMDAdN0
in MAME 2003 core, the player goes down correctly. (no mentioned bug)

**Comment by barbudreadmon** [comment]
I can't figure out this one, it doesn't seem related to the values retroarch send to the core, nor the type of analog controls i forced (there are actually 5 ways to handle analog output in fba upstream, and i forced the most basic one in the libretro port). I think i'll have to ask some help upstream.

**Comment by barbudreadmon** [comment]
It should be solved with my latest commit

**Comment by barbudreadmon** [comment]
I close.
