### ISSUE TITLE
Fire Shark doesn't work in libretro windows/x64

### ISSUE THREAD

**Issue by litaniast** [libretro/fbalpha#134]
It works well in latest version of standard FBA(0.2.97.40), but when I tried to play it in RetroArch Windows x64 version, it shows 'ROM ERROR 9' message and stuck in initialize screen.

**Comment by barbudreadmon** [comment]
Make sure you are using libretro-fbalpha 0.2.97.40 (the version is shown in bottom-left corner when you open the retroarch menu). This game works.

**Comment by litaniast** [comment]
No. I updated the 'latest' core (windows x64), still ROM ERROR 9 messages.

**Comment by barbudreadmon** [comment]
Try deleting retroarch-core-options.cfg in your retroarch directory.

**Comment by litaniast** [comment]
I tried but still get that error.

**Comment by barbudreadmon** [comment]
I can't reproduce your issue on any platform/os. If you want any more help, post your retroarch output. From what i see (rom error 9), the obvious reason would be you are using a wrong rom. So perhaps googling "fba 0.2.97.40 rom download" and getting the rom it suggests would be a good start.

**Comment by litaniast** [comment]
That romset works well in standalone fba(0.2.97.40 x64 ver) and mame(0.184). It's really strange.

**Comment by barbudreadmon** [comment]
It wouldn't be the first time a rom working in both mame and fba standalone wouldn't work in fbalpha-libretro.

I don't see anything wrong in your output, i don't know what's happening. Do you have a fireshrk.zip file in your samples directory ? Latest rom doesn't need it (the spu rom got dumped a few months ago) so perhaps deleting it would change something.

**Comment by litaniast** [comment]
Oops. solved. I deleted system/fba/hiscore.dat file (for mame 0.184) and works well now. Sorry for inconvenience!

**Comment by barbudreadmon** [comment]
Yes, it needs an older hiscore.dat, a compatible one is included in the repository : https://github.com/libretro/fbalpha/raw/master/metadata/hiscore.dat

I close

**Comment by barbudreadmon** [comment]
Some news : .41 will support newer format of hiscore.dat
