### ISSUE TITLE
Neo Geo CD cd sound very glitchy with cue/img

### ISSUE THREAD

**Issue by jhdgghost** [libretro/fbalpha#134]
I test in retropie 4.4 in a rpi3b+ the last updates in negeo cd emulation. I test different trurip (2017) cue/img games the games load perfectly but the cd sound is totally glitchy in all games tested.

**Comment by barbudreadmon** [comment]
Do you still have the issue after the last batch of commits ?

**Comment by barbudreadmon** [comment]
Most likely i just fixed your issue.

**Comment by jhdgghost** [comment]
Tested. The last commit fix the issue. Thanks.

I close the issue
