### ISSUE TITLE
Libretro - Fbalpha (neogeo) - Bios

### ISSUE THREAD

**Issue by wwark** [libretro/fbalpha#137]
Hi,

With MVS mode I tried to change the options BIOS in The Last Blade 2 but the default one is set.
"(default) MVS Asia/Europe ver. 6 (slot 1)"

How I can change it?

Thanks for your help.

**Comment by barbudreadmon** [comment]
Github is not a help forum, it's a place to report issues and share information.

Anyway i might as well answer now that you are here : 
- if you set "Force Neo Geo mode" to MVS|AES|UNIBIOS it will load the first bios it finds for those mode and ignore the second option
- if you set "Force Neo Geo mode" on DIPSWITCH, it will use the bios you set in the second option.

**Comment by wwark** [comment]
Sorry. Thank your for the explanation.
