### ISSUE TITLE
karianx - Lora victory graphic cutoff

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#138]
![karianx-190210-072710](https://user-images.githubusercontent.com/41223243/52527570-9fc3b380-2d05-11e9-928f-81f9ad5bd9d9.png)

**Comment by dinkc64** [comment]
Hi arnoldsecret, thanks for the bug report!
Unfortunately with this one, the bug is in the game code or graphics roms, and it's nothing that can be fixed in emulation.
