### ISSUE TITLE
Unable to use unibios 3.3

### ISSUE THREAD

**Issue by ArcadeTV** [libretro/fbalpha#143]
The automatic selection of the unibios makes all efforts to use my own unibios useless.
I'd love an option to tell fba which particular file to use, manually.

Anyways, thanks for all your great work!

**Comment by barbudreadmon** [comment]
Right now, fba doesn't include support for unibios 3.3 in its romsets. But you could rename your unibios 3.3 to "uni-bios_3_2.rom", then move it to neogeo.zip (we don't check crc on unibios files)

**Comment by ArcadeTV** [comment]
Thank you! That's what I did and it was still loading the 3.2. I'll double-check and delete the renamed 3.2. from the zip in all dirs where neogeo.zip can be located.

**Comment by ArcadeTV** [comment]
I experimented a bit... When I rename my 3.3 to uni-bios_3_2.rom then 3.1 gets loaded.
When I delete any other unibios from the archive the emulator freezes.
Changing MODE from unibios to dipswitch and select the 3.2 manually it falls back to standard mvs bios I think. Any way - it doesn't work.
Is there any other way to tell the emulator e.g. via CLI what bios to load and ignore the automated behaviour?
Thanks!

**Comment by barbudreadmon** [comment]
There is not, if renaming doesn't work, you'll have to wait for support upstream, sorry.
