### ISSUE TITLE
mtlchamp - slow gameplay speed

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#148]
game's running at 45fps, sound is also slow, maybe tied to framerate?

same game running on mame2003-plus runs better, and my hardware's stronger than the pi3b+.

**Comment by thomasgoldstein** [comment]
You may want to specify your hardware specs.

**Comment by barbudreadmon** [comment]
@arnoldsecret Not much can be done about it, the game is 3 times slower than a cps3 game, which is the limit of what a pi3b+ can emulate, maybe try : 
- rising frameskip in core options
- using the 32bpp thing in core options (it seems this option can improve rendering speed in some konami games)
- using cyclone in the core options (if you are on arm32)
