### ISSUE TITLE
ssoldier - background issue

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#150]
![ssoldier-190219-184703](https://user-images.githubusercontent.com/41223243/53009623-e5efe400-3476-11e9-88f1-05cd9a9e46db.png)

**Comment by dinkc64** [comment]
Thanks, something apppears to be going haywire with the scroll registers - I'll have to dig deeper tonight :)

**Comment by dinkc64** [comment]
Thanks again for the bug report!

![aps](https://user-images.githubusercontent.com/12570148/53135751-70edde80-354a-11e9-9ef2-5c832ff4d7af.jpg)
