### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by hobarrera** [libretro/fbalpha#151]
Hey! I'm packaging this for Arch/AUR, and I don't see any LICENCE or COPYING file in the repo, and the README doesn't specify anything.

Under what licence is this project distributed? Could you please add such a file to the repo? :)

**Comment by Oggom** [comment]
https://github.com/libretro/fbalpha/blob/master/src/license.txt

**Comment by hobarrera** [comment]
Ah, thanks, I hadn't looked inside `src`.

Would it be okay to add a symlink in the root of the repo (`/LICENCE`) to that?

**Comment by hobarrera** [comment]
Huh, that file states that MAME is licenced under the GPL, so, if this repo contains code from mame it MUST be distributed under the GPL, not another licence.

**Comment by fr500** [comment]
MAME wasn't always GPL, as long as the files haven't been updated from MAME since the license switch that doesn't hold.

Not sure if it's the case ofc.
