### ISSUE TITLE
iqblock - stuck in diagnostic screen

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#155]
![iqblock-190225-132229](https://user-images.githubusercontent.com/41223243/53315879-70659700-3900-11e9-9a9f-273c0f30549f.png)

Commit 9c55533 added this and grndtour to the gamelist. grndtour works.

**Comment by dinkc64** [comment]
Thanks for the bug report!
A fix will be in tonight.

best regards,
- dink

**Comment by dinkc64** [comment]
The fix is in the main repo, thanks again for the report! :)
You might need to go into the dips and turn off "Service Mode" after the update.

**Comment by arnoldsecret** [comment]
can't figure out how to turn off service mode in retroarch though

**Comment by dinkc64** [comment]
Hmm I don't know either, maybe @barbudreadmon can help?

**Comment by barbudreadmon** [comment]
@arnoldsecret @dinkc64 dipswitches are in core options.

**Comment by arnoldsecret** [comment]
![untitled](https://user-images.githubusercontent.com/41223243/53493967-a5781200-3ad7-11e9-8aa7-52c9d5904ac4.png)
