### ISSUE TITLE
Combatribes - missing Player 3 "coin"

### ISSUE THREAD

**Issue by Dochartaigh** [libretro/fbalpha#156]
The Combatribes, on FBAlpha .39, Retropie 4.2, Player 3 is missing the option to select a button for coin - so instead of this game being 3 player, it's only possible to play it 2 player.

**Comment by barbudreadmon** [comment]
You are right, player 3 seems to lack a coin button, thanks for the report.

**Comment by Darknior** [comment]
Arg so bad i don't see it, thanks for the report.
For the moment @gamez-fan works on MAME 2003, but maybe later if i work on FBA he can solve this ?

**Comment by gamez-fan** [comment]
@Darknior ya need to stop putting my name forward for every fix that needs done :)
barbudreadmon has this one more than covered!!!.

Regards

**Comment by Darknior** [comment]
Scuse me, it's only to be sure you read it. After you can, want or not do it, It is an other problem :p

**Comment by Dochartaigh** [comment]
Lol guys. Thanks for all the enthusiasm everyone - this could also be that I'm one version back with my installation (running .39 instead of .42 romset, and on RetroPie 4.2 instead of 4.3) - I'll be upgrading in the next week or two when I get time.

Since you all seem helpful (which is friggin awesome I must say!), in regards to 3 and 4 player functionality, it seems like the ability to turn on the 3 or 4 player mode is missing for Bucky O'Hare and Cowboys of Moo Mesa (and I dug through pretty much every single option menu I could find). When I switch those games over to mame2003 (which I don't use much since it's a pretty old 0.78 romset on the RP3) those two games (and Combat Tribes) work properly with 3+ players.

Also, on the same lr-fbalpha build as my initial post, I'm finding many games where the controls have the proper default button mappings for Player 1 and Player 2 (i.e. defaults of Y and B for attack and jump), BUT they'll have different buttons assigned as the default for Player 3 and/or Player 4 (which might have Y and X, or Y and Left Trigger for some random reason). If you need exact ROM names and which players are different, that might have to wait until I start another build in the next week or so - OR, I can give you a list of what games I changed controls on last night (where I can sort the .rmp controller configs by date and see what I worked on last night - would be a short list of maybe 20 games and a bunch of those will have switched mappings for different players).

**Comment by barbudreadmon** [comment]
Answer from dink upstream : 

> For the Combatribes there are only 2 coin inputs.  For 3 player, set the dips to "# of players:" 3, reset, put coins into any slot and press 1p 2p 3p start to start the players

So basically, you need to go in core options, set the "number of player" dipswitch to 3, return to game, add enough continue through coin button on controller 1 or 2, then press start on all controllers.

About your issue with player 3/4 having different buttons, are you using the "arcade" setting for "Control scheme" in core options ? You don't want to do that, using autoconfig or a pad/stick properly mapped with recommendations from https://wiki.libretro.com/index.php?title=RetroPad + "gamepad" as "Control scheme" in core options is the proper way to get a good mapping. What you are using is an option for people who don't use the reference layout from libretro (you can follow the discussion about this here : https://github.com/libretro/fbalpha/issues/141 ), and its name is misleading since it is unrelated to the use of an arcade stick. Also, in recent lr-fbalpha, the "Control scheme", "Neo Geo gamepad scheme" and "L/R gamepad scheme" moved from core options to device types in "Quick Menu > Controls", and the arcade setting was removed.

**Comment by Dochartaigh** [comment]
Thanks for the info @barbudreadmon. I did make sure that option was turned on for 3 players (then "save game overrides", and reset the game). How many coins are we talking about on player 1 and 2? I usually press "select" maybe ~5 times to give each player credits, and since I still couldn't get player 3 to work I did another round...so that's probably 10 coins per player 1 and 2 and still no-go on getting the 3rd player to join the game. I can definitely try this again over the weekend to see if I screwed up somewhere though.

For the controller control scheme, I'm not home to double check, but I swear the default setting was  "arcade" without me ever touching it. I'm glad you linked me to that post - I actually [posted on the RetroPie forum](https://retropie.org.uk/forum/topic/13700/how-to-save-game-remap-files-for-mame-properly) the other day about something similar and @dankcushions chimed in there too - I haven't had enough time to formulate my thoughts and test enough to intelligently reply there quite yet... (plus I think my biggest mistake was trying to get a scheme which worked for a regular SNES/PS/Xbox controller AND my fightstick - which I just don't think will work).


So my big question to you is if I update to RetroPie 3.1, and update lr-fbalpha to the most recent version, can you please tell me how I could get a controller config like the below diagrams setup for my Fightstick? (I made these graphics for that other post, but they may be better served here since I mostly use lr-fbalpha and not lr-mame2003 which I think Dankcushions maintains).

[img]https://i.imgur.com/hO4O06U.png[/img]

Then for Neo Geo games:
[img]https://i.imgur.com/HbfwFpC.png[/img]

**Comment by barbudreadmon** [comment]
I don't have issues registering 3 players as long as i have 3 credits. Perhaps the .39 release had some kind of issue with this game if you need more.

On retropie 4.3, with the latest lr-fbalpha, and without any change to the default controller configs and assuming autoconfig map your arcade stick as follow ( that's how 99% of arcade sticks from the last 20 years are supposed to be mapped with autoconfig ) : 
`Y X R1 L1`
`B A R2 L2`

The gameplay in fbalpha would look as follow : 
- For neogeo games, the device type "classic" would give you the neocd mapping (http://img11.hostingpics.net/pics/245741PadNeoGeo.jpg), and device type "modern" would give you an alternative mapping on fighting games (only ffurys, kofs and samshos), which is a mimic of recent PS/Xbox opus for those games (i have to say i prefer this one, it feels extremely similar to street fighter 2 with the punch row on top and the kick row on bottom, weak column on left, strong column on right).
- For all other games, i highly recommend the "modern" device type if you are using an arcade stick mapped as i shown, you would end up with the mapping you shown on 6 buttons fighting games, and for other games it would look like this : 
`(3) (4) (5) (7)`
`(1) (2) (6) (8)`
NB : there are very few 5+ buttons games outside of fighting, and i don't think there is still one where this mapping feels wrong, feel free to post a report at https://github.com/libretro/fbalpha/issues/102 if you find one.

If you own an exotic arcade stick, feel free to post a pic or the model.

Also, feel free to post a list of games where you think the player 3/4 controls don't work even with the correct dipswitches set, i'll test them, i just tried moomesa and bucky and couldn't get player 3/4 to work either, so i suppose there could be an issue, perhaps @gamez-fan, which is more involved than me with upstream, know something about it ?

**Comment by Dochartaigh** [comment]
Thank you for the detailed post @barbudreadmon - it’s extremely helpful. So this Friday night I’m trying this again. Brand new RetroPie 4.3.0 install. I’m using my 8-button Fightsticks with Device Type set to Modern as you suggested, which are mapped like below:

(Y) (X) (R1) (L1)
(B) (A) (R2) (L2)

Street Fighter type games are perfect - top row is punches, button row is kicks. Awesome! 




Alien vs Predator, a 3-button game, isn’t how you say it should be though. You said it should be:

(3) (4) (5) (7)
(1) (2) (6) (8)

Mine is instead:

(.) (.) (.) (.)
(1) (2) (3) (.)

Now this I LIKE!!! In the actual AVP arcade cabinet these 3 buttons are all in a row on most 3-player cabs (Fire, Attack, Jump), so this is perfect. BUT, when I’m using a regular PS3 controller for Player 2, with “Classic” (the default) Device Type, You would think the 4x face buttons (A B X Y) would be buttons #1-4, right? They’re not. #3 (jump) is mapped to R1 for some reason, which is a pretty bad place for doing all those jump+attack moves (and painful for my hand to be honest). If I switch this to Modern, and play on that same PS3 conreoller, #3/jump is R2 now. Arcade Device Type is also badly setup. 
 



Armored Warriors, a similar 3-button game to AVP (but Attack, Jump, Secondary Weapon all in a row), is laid out perfect once again for the Modern Device Type on my Fightstick (not correct to the official layout you mentioned, but how I like it and how the real arcade cab is setup, so that’s great), but again on  PS3 style controller in Classic mode, it puts the 3rd button onto R1 again…. Ideally the PS3 style controller should have those three buttons in a row, which would be Y, B, A (so ideally the bottom 3 buttons at 9, 6, and 3 o’clock - just a suggestion ;) In a 1 through 4 button game the shoulder buttons should never be used IMO.




Bucko o-Hare (which we know more than 3 players doesn’t work, but is another 3-button game), this one (per GamesDatabase.org which is where I pull most of these arcade button layout templates from, FYI), should be Fire (1), Jump (2), Special (3) all in a row. On Fightstick/Modern, I’m getting:

(1) (.) (.) (.)
(2) (3) (.) (.)

So logic would say this one should follow the two previous 3-button games I tried right before, right? It doesn’t. PS3/Classic layout is doable - at least #3 is mapped to a face button and not a shoulder/trigger button (which again isn’t consistent with the other games I just tested…).




If we switch to the more simple 2-button games, where most games are Attack + Jump, you said #1 and #2 should be:

(.) (.) (.) (.)
(1) (2) (.) (.)

That would be great, right? Identical to the arcade cabs where the buttons are roughly quasi-level to each other (they do like their slight angles on many cabs I’ll admit though), but the buttons are still clearly left and right of each other. But on the 10+ 2-button games I tried, it’s laid out like this with the bottons on top and bottom of each other:

(1) (.) (.) (.)
(2) (.) (.) (.)

So not a huge deal breaker, just not following any sort of logic I can comprehend. 




So what I’m getting at here is I’m still looking, and would absolutely love, for some sort of logical layout which works across all games. If I could go by this default you posted:

(3) (4) (5) (7)
(1) (2) (6) (8)

At least I would instinctually know where buttons #1 and #2 for 2-button games go, where #1, #2, #3 for 3-button games go, and for those SFII type games know the top and bottom rows are punch and kick…but instead nothing is following logic across all these games I tried. Did I screw up something here and I’m just not getting it? (that could very well be the case…I’ve been working on this, and this super-long post, for over 3 hours now, and it’s 3:45am right now…).

Please let me know if I can help in any way with these mappings, if you want me to post in that #102 topic - anything I can do I’ll be glad to help – and I REALLY hope this post doesn’t come across as a criticism - it’s simply me explaining the couple test games I always run through and what I found in this small sample of games. Thank you.

**Comment by barbudreadmon** [comment]
Well, that's not how things are mapped in the code, so i can see 3 possibilities : 
- Retropie 4.3.0 doesn't use the latest version of fbalpha-libretro
- You have some remap files imported from a previous installation
- Retropie do weird things with controller mapping (i know recalbox use its own abstraction layer for mapping, instead of using retroarch's one, perhaps retropie do something similar)

**Comment by Dochartaigh** [comment]
When I hit Select+X, RetroPie's RetroArch menu is telling me "1.6.7 – FB Alpha v0.2.97.42 928a4d6". Is "1.6.7" the version of FB Alpha, and is that the newest? I didn't update everything to the most current as updating from 4.3.0 to 4.3.3 last week bricked TG16 from using the default lr-beetle-pce-fast emulator for PC Engine CD games (could have been a fluke, but RetroPie does this to me all the time so I didn't want to risk it).

For my Romset, I used CLRMamePro to convert my merged set to non-merged and it was validated 100%.

Definitely not a single file besides ROM's transferred over so no config files in this fresh install. I will post back to my topic on the RetroPie forum where @dankcushions chimed in to see if he has any insight.

**Comment by dankcushions** [comment]
retropie doesn't do anything special with mappings. it just sets up a joypad autoconfig for your device.

but, it looks like https://github.com/libretro/fbalpha/commit/928a4d66b9bf80a4ad1652298db30803814017ef in 4.3 is not latest (it's quite recent, but still after a lot of input related updates). you should update lr-fbalpha via source, via retropie-setup.

**Comment by barbudreadmon** [comment]
That's a commit after i started refactoring my functions, but before i started looking into every game mapping to fix them. The mapping you got is not surprising if you use this commit, i highly recommend updating, latest commit also fix some issues with neogeo bios and add some speedhack for http://www.system16.com/hardware.php?id=817

**Comment by Dochartaigh** [comment]
Bucky/Moo Mesa confirmed working! Thanks for all the help everyone. Only had to remap one game so far (Alien vs. Predator – jump and attack are across from each other at A and Y which makes it very hard to do the common jump+attack constantly).

**Comment by barbudreadmon** [comment]
After taking a look at https://i.pinimg.com/originals/47/55/0e/47550e9450ac8b9ef1143e7e400c3111.jpg , it seems the layout of this one is wrong indeed, i'll fix this in my next commit
