### ISSUE TITLE
latest version of fba .42 causes 2 specific games to not work

### ISSUE THREAD

**Issue by MindController** [libretro/fbalpha#159]
Updated to .42 using retropie, and now both Violentstorm and Metamorphic Force refuse to work.  I have used clrmamepro to convert to .42 using the updated dat file, but both games have bad sectors show up on the ram rom check.  But it's only these games, no other games I have based on the .40 fba rom set have any issues.

Possible for anyone else to try and run these games to see if the issue is on my side?

**Comment by retro-wertz** [comment]
both of those games run fine, at least the parent roms.

![screenshot_2017-11-22_16-36-56](https://user-images.githubusercontent.com/23315382/33117503-a50fed42-cfa3-11e7-84b3-fc2c180ea5da.png)
![screenshot_2017-11-22_16-38-26](https://user-images.githubusercontent.com/23315382/33117506-a5da7d00-cfa3-11e7-9364-07d15ec3b9bb.png)

**Comment by barbudreadmon** [comment]
Try removing the .nv files corresponding to those games from your save directory, they could be corrupt or not compatible with the current version of fbalpha.

**Comment by retro-wertz** [comment]
@MindController  are you by any chance using retroarch 1.6.8 or newest 1.6.9?

Interestingly, i update retroarch to latest version and these games now shows bad ram areas with REWIND set to ON. turning off REWIND makes the game work(probably affects other games too...

A similar issue with rewind in latest retroarch also causes loading issue in PC-FX if rewind is set to ON.

**Comment by MindController** [comment]
@retro-wertz - yes im using the newest 1.6.9.  And that was the issue.  With rewind enabled, violent storm and metamorphic force gave me the fails on the ram rom check, but disabling fixed the issue.  Still very strange it only affects 2 out of the 10 arcade roms I have for Final Burn Alpha.  But thanks so much for helping me get it resolved!

**Comment by fr500** [comment]
@retro-wertz I don't think the crash is related at all.
I suspect some pointers may be included in the savestate so when rewinding some data ends up as garbage.

**Comment by retro-wertz** [comment]
@fr500  yeah, i was about to update this post :D

**Comment by barbudreadmon** [comment]
Both those games are from the same driver (https://github.com/libretro/fbalpha/blob/master/src/burn/drv/konami/d_mystwarr.cpp), so the pointer issue would make sense

**Comment by barbudreadmon** [comment]
Reported upstream after doing some test with fba standalone : http://neosource.1emulation.com/forums/index.php?topic=1731.msg24737#msg24737

**Comment by barbudreadmon** [comment]
It should be solved, let me know if you still have issues.

**Comment by retro-wertz** [comment]
as always, great work. Works fine on my end. rom starts with rewind ON now.
