### ISSUE TITLE
[Linux, ARMhf] Gunbird 2 freezes

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/fbalpha#164]
Gunbird 2 freezes on Ubuntu 14.04 ARMhf soon after you load it, you just get a black screen. Using the Odroid U3 

Tried on Android, it's working. Need to test on others distro & raspberry pi

It works in FB Alpha 2012

**Comment by barbudreadmon** [comment]
System is freezing or just the game ? What's the exact commit ?

**Comment by barbudreadmon** [comment]
I don't know why this issue got closed when i commited my fix.
My commit seems to do the trick, also the game (actually every psikyo sh games except soldivid) only crashed when the speedhack in dipswitches was disabled.
