### ISSUE TITLE
Support for pastelis?

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#164]
Pastel Island, prototype SSV game.

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=pastelis&search_id=

**Comment by dinkc64** [comment]
arnoldsecret, thanks for reminding me.  I'll see what can be done about adding it :)

**Comment by dinkc64** [comment]
5 hours later.. I got the easy part done - the game loads up and runs, but some graphics issues need to be worked out.  Will try again tomorrow!

**Comment by arnoldsecret** [comment]
any updates?

**Comment by dinkc64** [comment]
I can't get the graphics quite right, this game uses a linescroll mode in the background layer that is confusing.
so, I'm going to need help from a friend on this one, I just have to wait until he is not so busy to ask :)
Probably will be a couple days.

**Comment by dinkc64** [comment]
got the code right, finally!  I'm terrible with advanced graphics stuff, but managed to figure it out.
There is a drawback though, ssv games now need a bit more cpu% to render the graphics.
p.s. it might be a day or 2 before checked in, need to do some testing first..
![pastelisland](https://user-images.githubusercontent.com/12570148/54484486-64edf780-483e-11e9-915d-e9ef8119ae9e.png)
![dynagear](https://user-images.githubusercontent.com/12570148/54484487-67505180-483e-11e9-938f-389f8c3e04b2.png)

**Comment by dinkc64** [comment]
it's been checked into the main branch
