### ISSUE TITLE
CPS3 floating point exception

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/fbalpha#168]
It seems CPS3 games are failing to load with a floating point exception starting with the 'refactoring msvc and MAX_PATH macros' commit:
https://github.com/libretro/fbalpha/commit/81b7c4090a720e4ecd78d9a4644a14f50448503b

**Comment by barbudreadmon** [comment]
Except if you got a different issue than mine, the commit at fault was https://github.com/libretro/fbalpha/commit/6d11010a963de4837e015f5f0caaa140e21f0ea0
Can i close or do you still have an issue ?

**Comment by retro-wertz** [comment]
i had the sam issue with cps3 as @hizzlekizzle did... i can confirm the latest commit now is able to load cps3 romsets.

**Comment by hizzlekizzle** [comment]
My git bisect pointed to 6d11010 as the offending commit but then I manually built the one before it and it failed, too, so that's the one I figured introduced the problem. Regardless, if it's working in latest, I'd say we can close it out :)

I'll go ahead and close the issue and do some testing this evening and reopen it if the problem persists.
