### ISSUE TITLE
Hiscore .hi files should be in save_dir, not system_dir.

### ISSUE THREAD

**Issue by dankcushions** [libretro/fbalpha#171]
Currently both the hiscore.dat and .hi files are sourced from (and the latter written to) the system_dir.

The general rule is that system_dir is for support files (BIOS, metadata, etc), and save_dir is for user data (save files, etc). So, .hi hiscore files should be located in the save_dir, not system_dir, and, the hiscore.dat should remain in system_dir.

Currently the two use the path same variable, so this would have to change.

**Comment by barbudreadmon** [comment]
My last commit should fix this (moved the .hi files to the same dir as .nv and .fs files).
