### ISSUE TITLE
3x punch and kick macros for CPS 1, 2 and 3 games not saving after exit

### ISSUE THREAD

**Issue by NightmareSteam** [libretro/fbalpha#176]
If I assign the 3x punch and kick macros to buttons in the option menu and then exit the emulator the macros are not assigned when I reload the game. Macros for Neo-Geo titles are saving properly but not the macros for CPS 1 2 and 3 titles.

**Comment by barbudreadmon** [comment]
What version (with commit) of this core are you using ?

**Comment by NightmareSteam** [comment]
Using v0.2.97.42 with commit caebb35

**Comment by barbudreadmon** [comment]
I have a guess at what's happening (probably some invalid char in the generated core options), but i'm wondering if it is worth fixing (we have been talking with @fr500 about handling macros/autofire on the frontend side and removing those core options).

**Comment by barbudreadmon** [comment]
I prefer keeping this issue open as a reminder, i'm still waiting for news about the frontend macros/autofire support, and i guess i'll end up fixing this issue if the support don't come in the next few months.

**Comment by fr500** [comment]
yeah sorry about that, I haven't figured a way yet it's still in my list of stuff I definitely want to do but I have no ETA.

**Comment by barbudreadmon** [comment]
The issue was indeed some character not being accepted by the core option system.
