### ISSUE TITLE
msvc2017 regression ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/fbalpha#178]
@claudiuslollarius @albertofustinoni @twinaphex Lately, i noticed every commit is tagged as failing because of msvc2017. Seems to me like "offsetof" is buggy in msvc2017 (i found topics like this one : https://developercommunity.visualstudio.com/content/problem/96174/offsetof-macro-is-broken-for-nested-objects.html). Could you take a look ?

**Comment by barbudreadmon** [comment]
I merged the PR (hot?)fixing this, i also asked upstream about it (they use msvc for their releases).

**Comment by claudiuslollarius** [comment]
This happens on the latest Visual Studio 2017 (15.5.6), so maybe you are thinking of a different issue?

**Comment by barbudreadmon** [comment]
The error was the following : 
> src/burn/drv/capcom/qs_c.cpp(144): error C2132: syntax error: unexpected identifier

I assumed it happened because of the offsetof (thanks for the useful error message microsoft...) and i guess i was right since replacing the offsetof macro fixed the build

It seems to be more related to this : https://developercommunity.visualstudio.com/content/problem/101755/compiler-error-with-offsetof-in-vs20173.html

**Comment by barbudreadmon** [comment]
Last commit properly fixed it, thanks for the help @dinkc64 :)
