### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by twinaphex** [libretro/fbalpha#183]
<retrobot> fbalpha: [status: fail] [recipes/apple/cores-ios-generic] LOG: http://p.0bl.net/168614
<retrobot> fbalpha: [status: fail] [recipes/apple/cores-ios9-generic] LOG: http://p.0bl.net/168615
<retrobot> fbalpha: [status: fail] [recipes/linux/cores-linux-armhf-generic] LOG: http://p.0bl.net/168616
<retrobot> fbalpha: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/168619
<retrobot> fbalpha: [status: fail] [recipes/apple/cores-osx-x64-generic] LOG: http://p.0bl.net/168620
<retrobot> fbalpha: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/168621
<retrobot> fbalpha: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/168622
<retrobot> fbalpha: [status: fail] [recipes/android/cores-android-jni-aarch64] LOG: http://p.0bl.net/168623
<retrobot> fbalpha: [status: fail] [recipes/nintendo/wiiu] LOG: http://p.0bl.net/168624

**Comment by barbudreadmon** [comment]
It was an issue with the new gyruss driver, i rollacked it.
