### ISSUE TITLE
Dip switches not working?

### ISSUE THREAD

**Issue by fr500** [libretro/fbalpha#185]
Hey,

I just tried messing up with dip switches in CPS1 and neogeo and stuff like freeze, flip screen and free play seem to be broken.

Tried SF2, and mslug.

**Comment by barbudreadmon** [comment]
@Luisjo96 Don't say "last update" when it's a 6 months old commit that caused the issue : https://github.com/libretro/fbalpha/commit/d6247cb2b7cf63cda91b2d9f3ec4237cd7eebfa0

I have to say i have no clue how the content of this commit is causing this issue. Any idea @fr500 ?

**Comment by barbudreadmon** [comment]
freeplay seems to work now.
freeze is acting weird (only works if it is enabled when the game is launched), and honestly i don't want to lose my time on this one so i guess i'll leave it as is.
Still don't know if flip screen ever worked.

**Comment by Luisjo96** [comment]
What okay then.

**Comment by arcadez** [comment]
Flip screen wont really be needed unless you wanna turn your TV's upside down :)

**Comment by barbudreadmon** [comment]
Reverted changes for this issue, those changes broke classic/modern controls, i won't try to fix this again since those dipswitches are useless anyway (what's the point of freeplay when you have infinite credits ?).
Feel free to make a PR if you find a working solution.

**Comment by fr500** [comment]
darn... I like freeplay for reasons, no big deal though, I never noticed it breaking things tho...

**Comment by sub-atomic** [comment]
Can't change the language of Go Go Mile Smile from Japanese to English (or Chinese or Korean for that matter) via the RGUI.

**Comment by barbudreadmon** [comment]
Ok, this bug is more annoying than i thought, i thought only freeplay/freeze/flip dipswitches didn't work but there are actually quite a few other dipswitch not working. I'll take a look again.

**Comment by barbudreadmon** [comment]
I tried something else, both controls and dipswitches seems to work properly now. Let me know if you still find an issue.

**Comment by barbudreadmon** [comment]
cps1/cps2 dipswitches are still acting weird, they work when you change them from core options then "restart" the game, they don't when you exit and start the game.

**Comment by barbudreadmon** [comment]
Dipswitches working fine including cps1/cps2, mapping not broken, orbs not broken (consecutive calls to `init_input` break this one ???), let's close this again...
