### ISSUE TITLE
Ghost Pilots Not Working Properly

### ISSUE THREAD

**Issue by OBurgerGuy** [libretro/fbalpha#190]
Player 1 controls don’t work and avatar plane doesn’t land into play field position, stuck on bottom right corner.

**Comment by barbudreadmon** [comment]
I don't know this game so i don't know what you mean by "avatar plane doesn’t land into play field position, stuck on bottom right corner".
What i do know is that player 1 controls are working properly, so that's a setup issue, the only thing i can tell you is to try removing any nvram file, hiscore file, remapping file, ... related to the game

**Comment by OBurgerGuy** [comment]
I was trying to properly explain I will shoot some video later and send it to you, I don’t know if I can explain it in text

**Comment by OBurgerGuy** [comment]
gpilots neo-geo

**Comment by OBurgerGuy** [comment]
It’s not a set up issue because everything was working fine up until the last update I did and it works just fine when I update from the binary instead of the source

**Comment by barbudreadmon** [comment]
As long as i can't reproduce it, it's a setup issue.
Tell me what the "binary version" is, perhaps i'll be able to help.

**Comment by furiadeoso** [comment]
Hi. @OBurgerGuy . Controls is working fine in this game at widows 32 and 64 bits. I can try to find someone  of my community with retropie to help, but I'm almost sure that deleting your settings (nvram file, hiscore file, remapping controls files, core-options...) as @barbudreadmon said it will be solved.

@barbudreadmon "binary version" is a FBA compiled core version (I can't say which exactly but of course not the last one) from the retropie repository.

**Comment by OBurgerGuy** [comment]
Like I said if I switch back to the full release of .42 if everything works fine it’s not a set up issue I will look further into it and take some video of the game having issues as well

**Comment by OBurgerGuy** [comment]
.42 binary release: https://nofile.io/f/wgSMzxkvSZ9/works.mp4

latest source build: https://nofile.io/f/dHKBJbdjUn1/broke.mp4

**Comment by OBurgerGuy** [comment]
by the way i have tested this also with emulated cpu overclock off, yes same results, the video was shot with overclock off as well.

**Comment by OBurgerGuy** [comment]
drawing a blank, where is nvram file located under retropie structure?

**Comment by furiadeoso** [comment]
Nice. But I insist you, if there is a flaw it would be specific to raspberry, which would be very rare. For me, last core ver. is perfect in windows 64 and 32 playing G.P. And the most sensible way to start discarding things is to remove (take a backup if you want, of course) the configuration files.
I don't have a retropie/rasp now, but it must be `retroarchroute/saves/fba`

**Comment by OBurgerGuy** [comment]
It’s not pi specific it’s a bug introduced in the latest source, the controls were modified and it’s mow broken

**Comment by furiadeoso** [comment]
Does it only happen in Ghost Pilot? Does not it happen in any other NEOGEO game?

**Comment by OBurgerGuy** [comment]
I haven’t checked the rest of the games I just came upon this late last night and I wanted to bring it to attention I have 129 other games I will have to check...

**Comment by OBurgerGuy** [comment]
Watch the videos, shows it right there

**Comment by OBurgerGuy** [comment]
barbudreadmon  knows my setup, we have hashed out an issue before, RPi3, Unibios 3.3, will be testing if the error occurs on stock bios shortly

**Comment by OBurgerGuy** [comment]
retropie has no nvram file for lr-fba

**Comment by OBurgerGuy** [comment]
Nope, still has issue on stock bios both us and jap

**Comment by OBurgerGuy** [comment]
im thinking that latest source build 2021f2d changed controls for cps3 and messed up the controls for neogeo.

**Comment by furiadeoso** [comment]
I watched the videos. Until you try what I'm telling you, you can not be sure that this is a bug.  In wich part of the code have been controls mofied? I only see CPS3 driver file.

**Comment by OBurgerGuy** [comment]
Please explain exactly what you want to try

**Comment by furiadeoso** [comment]
First try others neogeo games (played and unplayed by you if ypu can). two or three. Is happening too?

**Comment by OBurgerGuy** [comment]
Played 3 other shooters, all fine so far... no control or graphical issues yet

**Comment by furiadeoso** [comment]
Well. It seems that at least it is not an issue that affects the driver controls.  Try to delete remap file related to to gpilots in `\config\remaps\FB Alpha` if exist.

**Comment by OBurgerGuy** [comment]
Doesn’t exist

**Comment by OBurgerGuy** [comment]
Played gpilots in retroarch 1.7.1 lr-fba 0.2.97.42 8ad726a and bonproblem with graphic errors or controls

**Comment by OBurgerGuy** [comment]
tested: alpham2, androdun, blazstar, ctomaday, lresort, preisle2, pulstar, s1945p, sonicwi2, sonicwi3, twinspri, viewpoin and zedblade... no control or graphical problems, will be testing more

**Comment by furiadeoso** [comment]
`Played gpilots in retroarch 1.7.1 lr-fba 0.2.97.42 8ad726a and no problem with graphic errors or controls`
And the first non-working commit? Bisecting the error could be very useful.

**Comment by OBurgerGuy** [comment]
deleted both instances of highscore.dat and no change

**Comment by OBurgerGuy** [comment]
played gpilots using latest source compiled on another retropie setup (my sons) and no problems, something in this one installation is the issue.

**Comment by OBurgerGuy** [comment]
"And the first non-working commit? Bisecting the error could be very useful." i am not a programmer what do you mean?

**Comment by OBurgerGuy** [comment]
question, what is ETA for lr-fba .43? days, weeks. months, a year?

**Comment by furiadeoso** [comment]
I'm not too 😁.
Bisect: Last version (commit) working, first version not working.

**Comment by furiadeoso** [comment]
I've just readed your messages before the last. I think this issue could be closed. It's a retropie or config issue.

**Comment by OBurgerGuy** [comment]
It’s not a configure issue because it’s just with this installation and building from the source it works fine with the binary release also please answer my question when will .43 be released

**Comment by OBurgerGuy** [comment]
I can’t say this issue is closed but I don’t think it something that you guys can help me with whether it is an issue that you need to address I couldn’t tell you because I don’t know what the problem is, the controls work on every game except ghost pilots so I’m just gonna go back to the binary release .42 that works.

**Comment by furiadeoso** [comment]
I don't know. Two or three months I guess.

**Comment by OBurgerGuy** [comment]
Thank you, please leave this issue open for a couple days, I want to be sure, I will close it

**Comment by barbudreadmon** [comment]
@OBurgerGuy Stop switching back and forth from a version of fbalpha to another, be careful with oc, don't change bios too many times, and **delete .fs file every time you change any of this**. With the fact you replied too many times again, it seems you learnt nothing from your last issue... Also, don't ask for ETA, next release will be ready when it is ready, thanks.

**Comment by OBurgerGuy** [comment]
No the fact that I replied to many times is evident that I don’t understand how to git hub works and I’m using it as a conversation and that’s how I believe it should be as I’m not a programmer. I don’t switch bioses and I don’t delete the FS files every time as I wasn’t aware that this was an issue until now as I think that was a problem with ghost pilots, also I don’t switch back-and-forth from release to source, just when I’m trying to figure out what’s going on with source release, I usually have been using the up-to-date source releases until it caused a problem. I asked for an ETA because I figured if the The next release is going to be in a month or so I will just wait and use the binary release rather than try to build and keep up with the source release,  I am an emulator user of old-school I know not to ask for when games are going to be supported or when I release dates are but I was hoping in this instance someone would let me know that way I could just sit and wait,  thanks and you can close this if you like .

**Comment by barbudreadmon** [comment]
> I don’t delete the FS files every time as I wasn’t aware that this was an issue

That's why i said you learnt nothing from your last issue, i proved you your aof3 fs file generated when overclocked was breaking the game even after returning to normal clock.
