### ISSUE TITLE
Bug when loading options for game gaia crusaders

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#192]
I use retroarch 1.7.1 on Wii with FBA core to play gaia crusaders. I set the key to enter into diagnostic mode inside the game. When I go into game options in retroarch to change dip switch like number of lives, set continue on/off it keep settings in retroarch but when I check in the game the settings are still on default. Only free game play working...

I checked on Windows with FBA with the same game rom and when I change settings dip switch, it work for all settings.. it is like retroarch doesnt "apply" the changes to the game settings.

**Comment by barbudreadmon** [comment]
As you can see at https://github.com/libretro/libretro-super/blob/master/recipes/nintendo/wii , there is no wii version for this core, so you are probably using a flavor of https://github.com/libretro/fbalpha2012 . Be careful to ask the right people next time, thanks.

**Comment by cecilmax** [comment]
Hi, then why in makefile.libretro there is option to compile on wii platform ?? :)

**Comment by barbudreadmon** [comment]
There is a wii platform in almost all core's makefiles, but the wii is not powerful enough to emulate half of them.
