### ISSUE TITLE
Audio channel swapped..?!?

### ISSUE THREAD

**Issue by OBurgerGuy** [libretro/fbalpha#196]
When playing games like robo army (roboarmy), ghost pilots (gpilots) or alpha mission 2 (alpham2) (haven’t tested any more games, I’m sure there will be more if the game uses that stereo effect)
The nuance effects like explosion of enemies on the far left or far right are heard in the wrong speaker. Tested audio and speaker configuration and wiring, all is correct, tested on a tv with speakers with same results, also tested different installations/setups, all with same results... the audio appearance of swapped speakers.  

Using retropie with lr-fba core v0.2.97.42 e758230 on retroarch build 1.7.1

Anyone got anyone on this? Known bug? New bug? I just discovered it?

Please advise

**Comment by barbudreadmon** [comment]
Tested gpilots on my headset, explosions on the left heard on the left, explosions on the right heard on the right. This is not an issue with the core, closing.
