### ISSUE TITLE
Read ahead input lag feature and sound issues

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/fbalpha#197]
The new read ahead feature in the Frame Throttle menu can work with some games and cause issues with some other ones in fbalpha.

Viewpoint or Armed Police Batrider will have messed up sound, mainly the bgm.

Is there anything possible to do about that?
Cleaning up the save state or something?

Perhaps @Dwedit knows?

**Comment by barbudreadmon** [comment]
Hmm is that related to high cpu usage ? does the feature use the retro_serialize methods ?

**Comment by Tatsuya79** [comment]
It uses states yes, can't do without them.
Not a CPU limit in my tests.

**Comment by barbudreadmon** [comment]
netplay/rewind working properly with those games ? did you run them at normal cpu clock ?

**Comment by furiadeoso** [comment]
Hi! I've just spent some time doing netplay in Armed Police Batrider and all ok. I hope that helps. Tell me if you need something more

**Comment by Tatsuya79** [comment]
The problem happens at normal clock.
I don't do much netplay and never use rewind so I can't really say.

The problem could be that the save states need to be cleaned of any sound information?
I think that's what Dwedit was doing in several cores starting with snes9x.
That can be complicated in fba if every game has its particularities.

**Comment by barbudreadmon** [comment]
@Tatsuya79 well, 2 out of 3 features relying on retro_serialize methods work properly with sound information included, my guess is the read ahead feature is early beta and need some fix.

Removing sound data from the savestates in fba is not a realistic solution : it could affect other features and would require large amount of work on a per system basis.

**Comment by barbudreadmon** [comment]
I re-enabled USE_SPEEDHACKS in the neogeo driver, this code should be safe since https://github.com/libretro/fbalpha/commit/980171e5efff1730588c8a2d156f894b7655253b, is actually enabled upstream, and it seems to introduce something in the savestates related to sound. @Tatsuya79 let me know how it affects viewpoint and other neogeo games.

**Comment by furiadeoso** [comment]
Ok. I'll do ASAP, but certainly I'm very busy today. Thanks.

**Comment by furiadeoso** [comment]
I've just tested one minute metal slug in cross-play win64-android32 and seems to be ok.

**Comment by Tatsuya79** [comment]
Sadly it doesn't help for read ahead, same stuck notes in Viewpoint music.

**Comment by furiadeoso** [comment]
@Tatsuya79  Have you identified any FBA game or driver working well with read ahead? And what settings have you used to notice the effect? I would like to test it in netplay. Surely it will have undesirable effects, but I'm curious.

**Comment by Tatsuya79** [comment]
Dodonpachi works fine until the end, I remember playing some espgaluda too.

**Comment by Tatsuya79** [comment]
Run Ahead isn't working at all since I updated the core to 0.2.97.43.
The message "Core doesn't support save states, Run Ahead disabled." is always shown while save states are still working.

**Comment by barbudreadmon** [comment]
Well, if the core support save states and the feature says the core doesn't support save states, that doesn't seem like an issue in the core.

**Comment by furiadeoso** [comment]
@Tatsuya79 Have you been able to find out what happened?

**Comment by Dwedit** [comment]
Also how do I make MSVC builds?  Would like DLL with PDB file.

**Comment by barbudreadmon** [comment]
@Dwedit https://github.com/libretro/libretro-super/tree/master/recipes/windows
No idea how you use this since i'm a gcc user.

**Comment by Dwedit** [comment]
At least any idea how to build a non-stripped binary?

**Comment by barbudreadmon** [comment]
In gcc i build it with `-O0 -g`, toggleable by adding `DEBUG=1` to make command.

**Comment by Tatsuya79** [comment]
@furiadeoso Yes, I think run ahead was defaulting to 1 instance mode.
That would explain the sound issues.
[I opened this one in RA issues](https://github.com/libretro/RetroArch/issues/6849) about the most recent problem (sorry if that's too many).

**Comment by barbudreadmon** [comment]
What's the status of this ?

**Comment by Tatsuya79** [comment]
Unchanged.
It works only if you start run ahead in 1 instance mode (which causes sound issues with many games) and slows the emulation down after a while (after several minutes of gameplay with hard sync 0 + some frame delay, I have to remove the frame delay, then the hard sync).

**Comment by FrozenFish24** [comment]
As discussed in [this issue](https://github.com/libretro/RetroArch/issues/6849), a fix for this problem is to make `retro_serialize` and `retro_unserialize` not dependent on a prior call to `retro_serialize_size` having happened. This could be done by removing the if statements in each function, or performing `retro_serialize_size` as part of each function. Opinions?

**Comment by barbudreadmon** [comment]
@FrozenFish24 Commited, let me know if it works.

**Comment by FrozenFish24** [comment]
Yep, working properly. Thanks @barbudreadmon!

**Comment by Tatsuya79** [comment]
Yes that works thanks!
I have to see if that still slows down after a while now... but that would be a new issue.
Closing this one.
