### ISSUE TITLE
The End (stern) sound very low

### ISSUE THREAD

**Issue by UDb23** [libretro/fbalpha#199]
Installed .43 on Pi3 with Retropie.
"The end" still has very low volume sounds (compared to original machine and lr-mame2003). 
That game has sound effects + some "continuous beating" background music (can almost not be heard even with max volume). 
Thanks if you can have a look a this.

**Comment by barbudreadmon** [comment]
I'll take a look when i have some time, right now i'm working on the raiden2 issue.

**Comment by UDb23** [comment]
thanks, no hurry on that ;-)

**Comment by dinkc64** [comment]
fixed in fba official, will send the fix over via pm :)

**Comment by UDb23** [comment]
Thank you both for quick fixing!

**Comment by UDb23** [comment]
@dinkc64 Tested the fix today. Overall sound is now ok but unfortunately the background "pulsating" sound (not really a music) still can be heard only by turning the TV volume much higher. At that point the other sound effects are too loud.

At standard ROM settings and at same standard volume on the TV, you can hear that "background sound" well in both lr-mame2003 and lr-mame2010 (2010 being even too loud btw).

**Comment by dinkc64** [comment]
ok, we'll try for louder then :)

**Comment by UDb23** [comment]
Works fine now.
