### ISSUE TITLE
v0.2.97.43 new games are not listed in retroarch playlist

### ISSUE THREAD

**Issue by furiadeoso** [libretro/fbalpha#200]
Hi!
Maybe this is not a core issue. 
I have scanned some roms from the new romset and they do not appear in the retroarch playlist. I've updated info core files and databases.

Could it be because a database has not yet been updated in the repository?
Thank you.

**Comment by barbudreadmon** [comment]
> Could it be because a database has not yet been updated in the repository?

I guess you need to update something in https://github.com/libretro/libretro-database. Perhaps open an issue there or make a PR if you know what should be done.

**Comment by furiadeoso** [comment]
Ok. Thanks! :)
