### ISSUE TITLE
RetroPie 4.4 with FB Alpha, 1.71, v0.2.97.43, 8140a53

### ISSUE THREAD

**Issue by Dochartaigh** [libretro/fbalpha#201]
Hey all, you guys were awesome with fixing problems I had last time and you said to post again if anything else cropped up so here I am...

I just did a fresh install of the newest RetroPie 4.4 they released recently, on a new Raspberry Pi 3 Model B+. I updated FB Alpha from source so it complied the newest version possible which is listed as: 1.71, v0.2.97.43, 8140a53. I'm having trouble getting a bunch of 3 and 4 player games to work (which work in RetroPie 4.3 with 1.6.7, FB Alpha v0.2.97.42, 2021f2D). I did the normal things like hold start to get into the dipswitch menu, as well as Select+X to poke around the RetroArch menu (options submenu usually). Normally one of those by changing the players to 3 or 4 + maybe changing the chute/coin style to individual does the trick but not this time (unless they REALLY hid these options someplace I'm not used to). You guys fixed a couple of these same games last time it happened (I assume when some other software was upgraded) Anyway, here's the games which are giving me trouble:

Captain Commando 4-player won't work (changed both Coinage and Play mode to 4-player, nothing in the dipswitch menu to change the players).

G.I. Joe can't get 4-player to work either (no dipswitch menu, changed options to 4 player in RetroArch menu)

Growl lets me choose 4 players in the player select screen, but only 2 can ever actually play.

Mystic Warriors can only get 2 player working.

The Combatribes only 2 players.

Violent Storm

Cowbows of Moo Mesa shows 4 players but can't select player #4

Please let me know if you need any more info or if I can otherwise help. Thank you.

**Comment by barbudreadmon** [comment]
Try updating to the last commit, your issue could be related to https://github.com/libretro/fbalpha/issues/185 which i fixed yesterday.

**Comment by Dochartaigh** [comment]
Just checked them all out - your commit had to have literally been an hour before I updated (no kidding!). Everything works now except Violent Storm: player 3 has no way to choose a button to add a coin so they can't start the game. Even with Coin Mechanism set to "Common" you can't get the 3rd player to work.

Thanks for the update though. Everything else is running great!

**Comment by barbudreadmon** [comment]
Violent Storm is working perfectly : 
- Setting "Number of Players" to "3" allows 3 players
- Setting "Coin Mechanism" to "Common" allows players 1&2 to add coins to the common pool of credits
- If there is enough credits in the common pool, any player can join by pressing start.

I'm closing, if you still have an issue with viostorm that's definitely a setup issue, and you'll have to ask help on retropie's forum for this kind of issue.
