### ISSUE TITLE
ISI error on WiiU

### ISSUE THREAD

**Issue by cucholix** [libretro/fbalpha#202]
tried with one of the latest nightlies and upon loading any content I got this error
![img-20180506-wa0000](https://user-images.githubusercontent.com/16081693/39673232-05bd3f22-510f-11e8-9988-499946898b00.jpg)

this has been broken for a while on WiiU acording other users, I can bisect if needed.

**Comment by barbudreadmon** [comment]
To my knowledge, there shouldn't be a Wii u version of this core in the buildbot. I don't intend to fix it, there wouldn't be any meaning in fixing it : Wii u is not powerful enough to run this, unlike cheaper hardware like the rpi.

**Comment by fr500** [comment]
Actually it works and worked pretty well, broke down a couple of months ago, not sure if it's a RA change or a core change.

**Comment by cucholix** [comment]
it used to run full speed previous to .43 bump, I guess will keep the build prior to may 3rd, thanks for your input.

**Comment by fr500** [comment]
@cucholix can you try building the commit that worked with the latest RetroArch?
That would determine if it's a RA regression or a core regression

**Comment by barbudreadmon** [comment]
So, is the bump to .43 really responsible for this issue ?

**Comment by cucholix** [comment]
I've been hunting down a recent working fba for WiiU but the newer that I could find is from 27-03-18
git version: 923ab3b
fba alpha v0.2.97.42 | 91e2435

The more recent version that I tested where the problem start to happen was from 26-04-18

**Comment by barbudreadmon** [comment]
@cucholix content of the commits between 27-03 and 26-04 : 
- changes in android makefiles
- changes in neogeo, dodonpachi and irem m107 drivers

None of those changes can affect wii u globally. Either you are wrong about the commit working / not working, or the issue is in retroarch itself (@fr500 ?).

**Comment by dinkc64** [comment]
according to the stack dump: It looks like retroarch didn't even get to the fba core, or possibly something in the fba core structure define that retroarch is referring to is null.

**Comment by cucholix** [comment]
@barbudreadmon I test latest FBA core with an old RA build and it does work, so it's an issue within RA not the core, here's the System Info:

- Build date: may 12 2018
- git version: 923ab3b6f4 <---27-03-18
- 1.7.2 fba v0.2.97.43 d9d9750 <---12-05-18

Now moving up to hunt down when RA broke FBA WiiU

**Comment by cucholix** [comment]
It's fixed in last nightly, no idea wha't going on, but it works now...
