### ISSUE TITLE
Can't compile on Mingw w64 Windows right now

### ISSUE THREAD

**Issue by twinaphex** [libretro/fbalpha#207]
I wanted to look into some of the WiiU issues which mighjt be related to us using old libretro-common VFS/filestream code, however, I cannot even get to that part right now since the PC Windows version doesn't even compile right now.

See the compiler errors here-

https://hastebin.com/ikorehetul.lua

**Comment by fr500** [comment]
It built fine here

**Comment by twinaphex** [comment]
Removed the repo, did another git clone, now it compiles. No idea. Going to just close this then.
