### ISSUE TITLE
Can't load - Path issue on windows

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/fbalpha#208]
I got the latest set for 0.2.97.43, I updated the core, info files, database, then I scanned my roms.
When everything is done impossible to launch anything, I just get
```
[libretro ERROR] [FBA] Cannot load this game.
[ERROR] Failed to load content.
```
be it from playlist or trying to load the file directly.

After trying many things I use an old playlist I had and then games are starting fine!
The new playlist is using / in the file path while the old one was using \ .
Replacing them all, now the new playlist is working, direct file loading is still failing though.
So we're not correcting that automatically at some level.

latest RA and FBA, win7 x64

Or could be a RA issue?

**Comment by Tatsuya79** [comment]
Ok it's happening only from the QT WIMP menu after more testing.
Closing this.
I notice recent games such as world rally 2 aren't detected though.

**Comment by barbudreadmon** [comment]
Looks to me like a duplicate of https://github.com/libretro/fbalpha/issues/200 .

Database needs to be updated, you should open an issue at https://github.com/libretro/libretro-database .
