### ISSUE TITLE
Run Ahead ON - Hiscores not working

### ISSUE THREAD

**Issue by kikeminchas** [libretro/fbalpha#209]
## Description

When using run Ahead the Hiscores functionality does not work. It works fine when the core is started without using run Ahead.

### Expected behavior
Hiscores working as expected with run Ahead.

### Actual behavior

Hiscores not being saved, even if the game supports it 

### Steps to reproduce the bug
Use FBA, load a game that supports Hiscores (i used street fighter 2' hyper fighting. Hiscores.dat is placed in system folder. Hiscore option active in core options. Without run ahead, hiscores are saved as expected. With run ahead on, they are not.

### Bisect Results

NA

### Version/Commit
Retroarch 1.7.5 (Android 32 bits)
Retroarch 1.7.6 (Android 64 bits)

### Environment information

- OS: Android TV 8.0 / Android 9.0

**Comment by barbudreadmon** [comment]
The state of the hiscore file isn't part of the savestates, so it seems legit to me that it wouldn't work properly with runahead/rewind. I also have to say that having hiscores done through the use of those features looks a bit like cheating to me.
Depending if upstream is interested in implementing this or not, i might decide to tag this issue as "won't fix".

**Comment by barbudreadmon** [comment]
I gave it some more thoughts, if the hiscore pointer was part of the savestates, what about netplay : 
- more bandwidth usage ? it is game dependent and can be several kb
- host's hiscores would overwrite client's hiscores ?

And again, read ahead is about reducing **original hardware input lag**, hiscores done with it can't be called legit.
I'll wait a few more days to hear other ppl's thoughts.

**Comment by furiadeoso** [comment]
Hiscores are problematic for netplay. Even in the current state (being deactivated when netplay (or run-ahead as it seems)) I think it is potentially problematic if you first load the game and after activate the netplay host. That's why in my netplay community we have them disabled.

**Comment by barbudreadmon** [comment]
@furiadeoso yeah, as i tried to explain, the hiscore pointer being saved to hiscore files isn't part of savestates, so this feature can't work with special features involving savestates. On the other side, implementing this would cause more bandwidth usage, and client-side local hiscore file would most likely end up being overwritten by the host-side local hiscore file after a netplay session.

**Comment by furiadeoso** [comment]
Well, perhaps normal savestates could include hiscores but fast-savestates will not. But in this way run-ahead  will must not use fast-savestates and this could be a problem itself because I suppose big savestates is not desiderable for run-ahead.

**Comment by barbudreadmon** [comment]
I think all savestates apart from normal ones are tagged as "fast-savestates", so the core can't tell apart rewind, read-ahead or netplay. And yeah, disabling "fast-savestates" has a serious performance impact for drivers like cps3.
For now, i see a lot of cons and not a single pro : imho hiscores should be somehow legit, and i can't see a single situation where a hiscore could be called legit if savestates were involved in any way to produce it, except maybe netplay but that's actually the most problematic technically.

**Comment by barbudreadmon** [comment]
I opened an issue in the RA repo for this.
I'll close this one for now, whether or not i want to implement this, i don't have the means to do it safely at the moment.
