### ISSUE TITLE
sound support for Deep Scan

### ISSUE THREAD

**Issue by UDb23** [libretro/fbalpha#214]
Deep Scan (invinco/deep scan) has no sound and even latest mame does not provide sound.
The point is that vicdual machines had same mainboard but different specific soundboards.
On the other hand recently [support for sound ](https://github.com/mamedev/mame/pull/2192)daughterboard in N-sub (another vicdual rom) has been added (by writing a sample player) . Samples for Deep Scan are the same of Depth charge and are available. It should be possible to write a sample player for Deep Scan too.

**Comment by barbudreadmon** [comment]
Sorry, we are not accepting this kind of request. The support for this will be added when upstream decides to implement it.
