### ISSUE TITLE
Orbs (orbs.zip) on 2.97.43

### ISSUE THREAD

**Issue by Loggahead** [libretro/fbalpha#215]
I got my romset updated to .43 and have been testing games and found a game called Orbs that previously worked with fba 2.97.42.  In .43, the game loads but after the winners don't do drugs screen it just flashes Coin Error.  

1. Can someone else confirm that the same thing is happening to you?
2. If so, is this something that can be fixed?

Thanks in advance!

**Comment by barbudreadmon** [comment]
Upstream don't have this issue it seems, not sure what's happening here.

**Comment by Loggahead** [comment]
I'm on running on rpi3b and retropie 4.4.

**Comment by barbudreadmon** [comment]
Again, fixes for #185 were causing issues...
