### ISSUE TITLE
Samurai Shodown RPG regression

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/fbalpha#217]
I get this screen after starting a new game : 
![Shinsetsu Samurai Spirits - Bushidouretsuden-190415-190524](https://user-images.githubusercontent.com/10391265/56151437-8531e300-5fb1-11e9-83da-d6c5cdcebeca.png)

It was working properly at some point, maybe before the Fatal Fury 3 fix ?

**Comment by dinkc64** [comment]
Thanks barbudreamon, 
I need to do some tests, so it will be later tonight when I check it in.

**Comment by barbudreadmon** [comment]
No problem, on a sidenote i don't think the neocd emulator has those issues while it totally skips loading screen afaik, so maybe there is a better way to solve this.

**Comment by dinkc64** [comment]
they frameskip while the disk is loading, i don't want to do that for input -recording-breaking reasons.
like while (cd_accessing) {do frame}
Personally I like the loading animations, I will make it so ssrpg uses the slower speedhack method for now.

**Comment by dinkc64** [comment]
using 225 only adds 2 seconds to the loading time of Double Dragon (f.ex.), that's not too bad.
It's still near-instantly loaded if F1(ffwd in fbalpha) is pressed  :)

Thanks for the fix!
