### ISSUE TITLE
Looking for FB Alpha v0.2.97.42 DAT

### ISSUE THREAD

**Issue by Wilstorm** [libretro/fbalpha#217]
I'm not sure if this is the correct place to post/ask but I am looking for the FB Alpha v0.2.97.42 DAT or a repository of older DATs? I have a 0.2.97.43 set built but I want to rollback and test something but I can't seem to find a DAT anywhere. Searching Google always brings up this page, RetroPie, Reddit and some miscellaneous pages. Thank you.

**Comment by barbudreadmon** [comment]
By looking at the commits history, you can browse older version of the repository : https://github.com/libretro/fbalpha/tree/08cf5c6abbda2512d5ef73ef8483b849a34a7603

**Comment by Wilstorm** [comment]
@barbudreadmon - Thank you very kindly good sir I really appreciate it! ;)
