### ISSUE TITLE
Wii U Asterix bug green screen

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#218]
Hello, when I try to load the game asterix I just got a plain green screen. Stuck there...

**Comment by retro-wertz** [comment]
must be BE stuff since it works fine on linux

**Comment by cecilmax** [comment]
Ok, just tell me when fix will be apply, I will test it :)

**Comment by barbudreadmon** [comment]
@cecilmax it could take some time, upstream is really busy at the moment and i'm unable to fix this kind of issue by myself. 
By the way, did you try consecutive loading of games with my latest commit ?

**Comment by barbudreadmon** [comment]
Considering system18 is struggling on wii u, those konami games won't run on wii u. We won't fix this right now, this driver is too complex and require too much work, and it's pointless if people can't play it anyway (keep in mind that big endian technology is basically dead nowaday for an obvious reason : portability of software).
