### ISSUE TITLE
Wii U metamorphic force black screen with sound

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#219]
When I load the game, it show only black screen, I can insert coins, press start, the game seem to begin but just with black screen.

**Comment by barbudreadmon** [comment]
Well, could you please answer to #212 before opening more issues ? I would prefer working on one issue at a time, especially since fixing one could fix other games (asterix and metamorphic are both konami games and probably use common code). I'm marking this one as a likely duplicate of #218.

**Comment by cecilmax** [comment]
Ok no problem :)
