### ISSUE TITLE
Super Street Fighter II Turbo (very fast)

### ISSUE THREAD

**Issue by altiereslima** [libretro/fbalpha#220]
Super Street Fighter II Turbo in speed 1 (slow) is very fast.

![39677216-7b0df0f8-514d-11e8-9bb1-cd591ef31e16](https://user-images.githubusercontent.com/18044879/40869208-fc47f62e-65ec-11e8-998c-ac54d474354e.png)

**Comment by barbudreadmon** [comment]
I never noticed because i never played too much with service menu and dipswitches, but i guess you are right, speed 1 feels faster than speed 3. I'll test upstream to make sure it's not an issue with the libretro port.

**Comment by barbudreadmon** [comment]
After spending more time testing it, no, i actually think speed 3 is faster than speed 1, not by much though. Behavior seems to be the same upstream. Do you have any evidence speed 1 is not running at the same speed as it did on arcade ?

**Comment by altiereslima** [comment]
I tested on saturn and 3rd only.

**Comment by barbudreadmon** [comment]
Next time you post an issue, post this kind of information **first**... There is generally a few things that change when a company decide to port a game to another platform.

Anyway, both fba and mame seems to agree it was the speed on original arcade machine, i have no reason to not trust them, they know their stuff.

Closing.

**Comment by altiereslima** [comment]
Ok
