### ISSUE TITLE
Wii U PGM games performance issues Knight of Valour

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#221]
Hello,

I just try another game. Knight of Valour 1 Please note that game work perfectly on final burn alpha 2012 on wii U.

The game load but it is slowed down and sound is more than just choppy it is very very choppy. 

I also try oriental legend 1 and 2, same bug.
Note: oriental legend also work fine on fba alpha 2012.

I tested knight of valour 2: it is much more slower, the pgm logo is slide down the screen slowly at the beginning.

**Comment by barbudreadmon** [comment]
That's not a bug and not something i can fix, current fbalpha needs more ressources than the version from 2012. It's also probably going to get worse with every new release.

**Comment by cecilmax** [comment]
Ah ok, splitting the core into multiple smaller cores could it be a solution ?

**Comment by cecilmax** [comment]
Ok, so that mean the Wii U is not powerful enough for thoses games. Ok lets try to fix real bugs like asterix and d d crew, theses games have graphics glitches :)
