### ISSUE TITLE
Game knuckle bash dip switch language not working ?

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#222]
Hello,

I try to set dip swtich region to USA and the choice of game type at the beginnin its still in japan...do I do something wrong or it is not just working or it is a bug ? I try every region both on Wii U and on Windows, at the game still in japan... There must be a way to set the region because on youtube we can see the long play with the beginning in english..

**Comment by cecilmax** [comment]
Update: when I try to change the settings for the number of lives, it doesnt keep the changes. And the region too, I check under windows with the test mode and dip switch 3 doesnt change, whatever options I choose..

**Comment by barbudreadmon** [comment]
When you say windows version, do you mean the standalone version or the libretro port ?

**Comment by cecilmax** [comment]
Yes the standalone version, the bug it is in standalone version and on the wii u too :)

**Comment by barbudreadmon** [comment]
Well, it's fixed, so i'm closing.

**Comment by cecilmax** [comment]
Just test it and it work, thanks :)
