### ISSUE TITLE
PS Vita unable to load content error when loading any game

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#223]
Hello, I try to load a game and I always get the error: unable to load content yellow text at the bottom of screen every time on ps vita 3.60 hunkaku with retroarch 1.7.3

**Comment by cecilmax** [comment]
Ok, hmmm, well its the only details I see..the other cores can load games.. what kind of test I can do ?

**Comment by cecilmax** [comment]
Let me check again if I can find something more useful :)

**Comment by cecilmax** [comment]
Hmm, I just made other tests, I try to load from different folders, I make sure the folder have full permissions of read and write and I still cannot load any game. All other cores work perfectly ...

Here is what I do: I launch retroarch on ps vita 3.60, then I load fba core, I choose to load content, I browse to rom folder, I choose any game, in a second I come back directly to retroarch menu with a yellow text at the bottom: cannot load content, then it detect the gamepad again on port #0..

any suggestion what I can do for more tests ?

**Comment by barbudreadmon** [comment]
There is nothing useful in there. No i have no idea about more tests. I need the log, i can't do anything without it, and no i have no idea how to get them with console ports.

**Comment by cecilmax** [comment]
Ok let me check with the log

**Comment by barbudreadmon** [comment]
Closing as i never got the logs and other people are running this fine on psvita. Obviously a setup issue i can't help with.
