### ISSUE TITLE
Wii U Oriental Legend Plus - almost mute

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#224]
Hello,

I just try Oriental Legend plus, the graphics are 100% ok and the game speed too. But the sound is almost completely mute..no intro sound when the PGM Logo scroll down at the beginning and just a little sound when selecting character and once in the game, the sound is almost mute with just a thick sound every 5 sec like we are playing a dos game in 8 bit mode ...

Oriental legend 1 having serious sound issues too..

Other PGM game I try have the same issue:
Knight of Valour 1

If I try Knight of Valour 1 on fba 2012 the sound is 100% ok and oriental legend the sound is 80% ok on fba 2012, it is not perfect but is playable.

**Comment by cecilmax** [comment]
I know I already report bug with knight of valour but I thought I didnt explain the bug properly :)

**Comment by cecilmax** [comment]
Maybe it could be a good idea to build a seperate core just for pgm games ? :)

**Comment by furiadeoso** [comment]
Have you tried them also in Windows? PGM is a heavy machine, and a little more with the improvements of the latest FBA versions. maybe Wiiu can not with this driver.

I think Barbudreadmon explained it to you in another issue.

**Comment by cecilmax** [comment]
Let me try it tonight on windows.

If it is ok, maybe we can build a seperate core with just pgm games ? Like mame2003 ? Someone split mame2003 into seperate cores and it work well on wii :)

**Comment by furiadeoso** [comment]
I think it is very difficult and not a fba team priority. There is a lot of good drivers to be emulated yet.
By the other hand, I'm not sure that it could be a solution for these issues.

**Comment by cecilmax** [comment]
Ok, Ile let you know if it run ok on windows.

**Comment by cecilmax** [comment]
I wonder, how the game speed can be ok but not the sound ? Sounds need more cpu than the graphics gameplay ?

**Comment by furiadeoso** [comment]
I don't know. 
BTW a friend of mine have just tested Oriental Leyend Plus in raspberry 3 and has reported me that all is ok. At least in bbae566 fba core version.

**Comment by barbudreadmon** [comment]
> If I try Knight of Valour 1 on fba 2012 the sound is 100% ok and oriental legend the sound is 80% ok on fba 2012, it is not perfect but is playable.

Iirc even the rpi3 struggle with the current pgm driver if not overclocked, let alone `svg` and `killbldp` who won't run full speed even on a rpi3b+ at 1.5Ghz...

> the game speed too

When you say that, do you mean the fps shows 60 full time ? Or just the game "seems" to run at a good speed ?

> Someone split mame2003 into seperate cores and it work well on wii :)

Splitting helps with memory usage, not with speed, except if you spend weeks removing more unwanted parts of the code. No one here want to spend weeks fixing speed and memory issues for hardware slower and more constraining than a 40$ computer. Don't mention this again, thanks.

> Ok, could it be because wii u is big endian ?

Parts of the current pgm driver don't seem endian safe to me, perhaps they are the parts messing up with the sync. If i'm correct and we were to fix them, the games would be a lot slower though (while it seems you can somehow play full speed with no sound now, things will be totally different if the sound starts working alongside the graphics), which would be fine for ps3/xbox360, but probably not for the wii u and its 1.24Ghz cpu.

**Comment by cecilmax** [comment]
I can confirm the game run at 60fps..

So the bug may come from endian ?

**Comment by barbudreadmon** [comment]
> So the bug may come from endian ?

I'm not sure, https://github.com/libretro/fbalpha/blob/master/src/burn/drv/pgm/pgm_asic27a_type1.cpp seems to be endian safe, and seems to be the code used by those games. Also, do you prefer those games running at 60 fps with totally messed up sound (current) or do you prefer those games not running at 60 fps at all and having choppy audio (after potential fix) ?

**Comment by cecilmax** [comment]
To be honest, I dont really care about fps, as long as the game look good. I didnt try to lower the fps in retroarch, you think if I lower the fps, the sound will play ok ? Ill give it a try after work.

**Comment by furiadeoso** [comment]
@cecilmax keep in mind that a framerate drop is always is accompanied with a choppy audio effect. In my opinion it can be very annoying.

**Comment by barbudreadmon** [comment]
@cecilmax i just mean the game is currently running at full speed on your wii u because there is a bug, if the bug get fixed it won't run at full speed anymore, and most likely will be unplayable (it's pretty obvious considering your system don't handle intro in system 18 games).

**Comment by cecilmax** [comment]
Ok, so in other words, there is nothing we can do :)

**Comment by barbudreadmon** [comment]
@cecilmax Sorry, totally forgot to answer. Yeah there is nothing we can really do, between its endianness and its cpu speed, the Wii U is just an extremely poor choice to run fbalpha. Fixing all endianness issues in fbalpha would be too much work for little to no benefit (there is a 99.9% probability we'll never see big endian again in consoles and personal computers).
