### ISSUE TITLE
8 and 6 Panel arcade mapping in mame plus differences to fba

### ISSUE THREAD

**Issue by grant2258** [libretro/fbalpha#225]
@barbudreadmon I would like possible,  the cores could match up for people using both cores for using arcade control panels. As well as being able to use other cores in RA.

Im not asking you to change anything but if you could take the time to read a little explanation from me and why the modern core mapping isint core friendly mapping and give me your thoughts.

first of all I have a 8 dual button arcade panel. That is the only controls I use on this system.

So for it to be core friendly It has to me mapped as below for using psx or anything the uses the l-r mapping. This is basically mapping a 8 panel to a retropad properly.

Y X L R
B A L2 R2

The modern mapping I cant remember exactly is but the left and right are physically swapped in the sides. This messes you up when using lr on snes or psx because the l/r buttons  are the swapped.

Y X R L
B A R2 L2 

Mark has done a lot of work in the input system for mame 2003 plus and we can set a retropad per player that can be a gamepad 6 panel or 8 panel.

We have decided to go with the core friendly 8 panel setting 

Y X L R
B A L2 R2

to be core friendly so people with arcade panel can use other cores as well with a more friendly mapping standard as none are set at the moment.

The 6 panel is ok for both the systems as is 
YXL
BAR

This isint a major thing and you can feel free to close this I just wanted to make you aware of why we swapped the l/r buttons around the right way.

**Comment by barbudreadmon** [comment]
![stick](https://img.purch.com/o/aHR0cDovL21lZGlhLmJlc3RvZm1pY3JvLmNvbS9BLzAvNjA2ODg4L29yaWdpbmFsL0hvcmlfTWluaTRfMDEuanBn "stick")
This design represents most fighting sticks from the last 25 years (started with ps1 ascii).
![pad](https://images-na.ssl-images-amazon.com/images/I/412ypY7GgpL.jpg "pad")
The same applies to most fighting pads.

Street fighters 4 & 5 (and probably some of the remakes on ps1/ps2/ps3) also use R1/R2 for strong punch/kick.

So no, i have no intention to switch R1/R2 with L1/L2.

I don't really understand how it could mess other core mapping anyway, you are supposed to have a proper and standard mapping prior to launching any core as defined [there](https://docs.libretro.com/specs/retropad/#definitioncriteria). 
Selecting the mapping preset you prefer in fba comes after that.

**Comment by barbudreadmon** [comment]
You can also find a lot of other fighting sticks in https://github.com/libretro/fbalpha/issues/141 , you'll see there are a few oddballs (sadly, it would be hard to deal with all of them since they are basically one of a kind), but the main design is still : 
Y X R1 L1
B A R2 L2

**Comment by grant2258** [comment]
i posted on the mame thread most people do use other cores as well. We will just be setting up differently so people dont need to redefine there layouts for using other cores.

We are going to keep compatibility with all ra cores  so the 8 button panels will match the  retropad standard as closely as possible shape wise is the button layout

**Comment by grant2258** [comment]
there are many fighstick formats as well it wont work well for this

![sfjoypada](https://user-images.githubusercontent.com/6128601/41241938-22e2860e-6d96-11e8-9006-4a7cf7e20238.jpg)

**Comment by barbudreadmon** [comment]
This one fits well with the classic layout, 99% of controllers will fit well with either classic or modern anyway. I'm closing, no need to have 2 opened issues about this.
