### ISSUE TITLE
[Meta] FBA standalone repo just shuts off its issue reporting

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#226]
Someone on the neo-source forum had responded to the repo, trying to address the whole licensing issue. As a result, Barry turned off the issue reporting. Any thoughts?

**Comment by barbudreadmon** [comment]
I know, imho they need to fork the project (possibly under a new name to avoid confusion) as soon as possible.

**Comment by hizzlekizzle** [comment]
in the meantime, if anyone needs to file any issues, they can do it here.

**Comment by arnoldsecret** [comment]
dink made public this fork, https://github.com/dinkc64/FBAlphaFB, it's time to close this one.

**Comment by barbudreadmon** [comment]
Yeah, i forked the new repo, after i'm done porting the libretro stuff from this repo to the new one, i'll transfer all issues from here to the new repo.
Also, the name FBAlphaFB is only temporary, when the new name will be set in stone i'll make an announcement on libretro.com to notify users (ultimately, i want this repo/core to disappear)

**Comment by arnoldsecret** [comment]
would the FB Alpha 2012 cores be renamed?

**Comment by thomasgoldstein** [comment]
> would the FB Alpha 2012 cores be renamed?

Although I'm just a random guy and don't know all the details, I don't think so. I can't see why it should be renamed. But anyway, FB Alpha 2012 doesn't really matter anymore, does it? The latest version brings so many fixes, improvements and new games (without decreasing performances overall, afaik), that I can't see the point in hanging onto the 2012 version. Better kill it and forget about it to keep things simple, in my opinion.
