### ISSUE TITLE
Rom memory limit problem

### ISSUE THREAD

**Issue by ji125443** [libretro/fbalpha#226]
Requires to lift the memory limit, especially to modify the rom is very helpful

**Comment by fr500** [comment]
What?

**Comment by ji125443** [comment]
The basic program memory limit in the game compression ROM, for example: the problem that the basic program memory can not run when it becomes larger?

**Comment by fr500** [comment]
honestly I have no idea of what you are talking about.

**Comment by ji125443** [comment]
Example: the cde_23a .8 F memory in the dino.zip ROM compression pack is 512 KB, which can not run if its memory is expanded

**Comment by barbudreadmon** [comment]
I don't understand either. Try to explain what you are trying to do with simple words.

**Comment by barbudreadmon** [comment]
Oh ok, i think i understand, you are hacking a romset and can't load it in fba after expanding the size of a rom in it. Sorry but i don't think ignoring file size in the codebase is possible. You can still try asking help on standalone fbalpha's forum. Just try to be clearer than here...
Closing.
