### ISSUE TITLE
hiscores fbalpha

### ISSUE THREAD

**Issue by kacobathory** [libretro/fbalpha#228]
good evening
I want to put the support for hiscores, but I can not get it to work, I've already pegged the file and put it in several folders but it does not work, which would be the right way for the recalbox

**Comment by barbudreadmon** [comment]
Quote from https://github.com/libretro/fbalpha : 
> Copy hiscore.dat to SYSTEM_DIRECTORY/fba/

No idea where it is located in recalbox, ask them. Also, github is not a support forum, so i'll close.
