### ISSUE TITLE
Impossible to compile on Android NDK

### ISSUE THREAD

**Issue by han0idx** [libretro/fbalpha#229]
Im trying to compile on Android NDK for Windows but at the end of the compilation i have this error:
make (e=206): The filename or extension is too long.

**Comment by fr500** [comment]
How are you compiling?

**Comment by han0idx** [comment]
ndk-build -j8 on the jni directory

**Comment by fr500** [comment]
Well, I figure it's a problem with the linux commandline not accepting the argument (it's gonna be a looooong argument)

So the only solution I can offer you is use linux.
We're run into that for a few platforms in the past, it's solved immediately by building on *nix

**Comment by han0idx** [comment]
Is there an other solution than install new OS? Some people said the solution is to split Android.mk to multiples files as static libraries that maybe can avoid error on Windows

**Comment by barbudreadmon** [comment]
Since this is basically a sdk/os issue, i'll close
