### ISSUE TITLE
Move dipswitch options to a separate config

### ISSUE THREAD

**Issue by eckso** [libretro/fbalpha#229]
As you play games retroarch's default core options config grows bigger and bigger making it very difficult to review and edit static core options. Maybe calling the new config retroarch-rom-options, or retroarch-dipswitch-options can make more sense or/and putting them inside the system/fba folder. (same for "macro" options as I observe).

**Comment by barbudreadmon** [comment]
How RA deals with saving core options isn't core's business, also i think i opened an issue a long time ago about this in the RA repo.
Closing.
