### ISSUE TITLE
[Question] Ghosts'N Goblins: initialization screen on FBAlpha vs MAME

### ISSUE THREAD

**Issue by vanfanel** [libretro/fbalpha#230]
Hi! I have a small question, possibly not a bug, or at least a VERY minor bug.

Just out of curiosity: which is right? During initialization screens, colors are different on FBAlpha (all blue-ish) and MAME. How does the init screen on the real arcade look like?

**Comment by barbudreadmon** [comment]
No idea, i don't own the cabinet, try searching on youtube. If **recent** mame doesn't have the blueish initialization screen, i expect the cabinet to not have it either.
