### ISSUE TITLE
FPS very instable on SDL

### ISSUE THREAD

**Issue by han0idx** [libretro/fbalpha#232]
The FPS of the emulator is very instable with SDL even you force it at 60hz the average is about 90hz with high variations from 46hz to 150hz.
im compiling it by using SDL, but in windows seem ok.

So as i see the variable bForce60Hz = true; seems doing nothing to FPS of SDL.

Here the graph : https://prnt.sc/kmkrkx

**Comment by barbudreadmon** [comment]
This repository is only about the libretro version running under lakka/retroarch. I close.
