### ISSUE TITLE
FB Alpha 0.2.97.43 Core - martmasttw.zip not working

### ISSUE THREAD

**Issue by dallenc** [libretro/fbalpha#234]
Hi,

There is an issue with the above-mentioned core (as updated to the latest FB Alpha one on Retroarch Android).

The file martmasttw.zip simply refuses to load with the core despite having checked the contents against the .dat file as provided on Github.

Just wish to highlight this for completeness sake as there are other clones to choose from.

**Comment by barbudreadmon** [comment]
See https://raw.githubusercontent.com/libretro/fbalpha/master/gamelist.txt for the list of not working games.
