### ISSUE TITLE
Add 5 drivers which were removed by FBA 0.2.97.43?

### ISSUE THREAD

**Issue by twinaphex** [libretro/fbalpha#236]
@barbudreadmon It's up to you what to do with this, whether you want to still backport this to the fbalpha libretro core or whether you think it's a bad idea to diverge from upstream. In any case, I think the reason they were removed is petty and users should not have to suffer as a result.

However, I respect that you maintain this core so I leave the decision entirely up to you - whatever decision you take I am fine with -

You can check out the PR that was sent adding it back here -

https://github.com/libretro/fbalpha2012_neogeo/pull/24a

**Comment by barbudreadmon** [comment]
@twinaphex i decided to add them now, i just hope they are working (didn't test them).
