### ISSUE TITLE
Road Fighter (roadf) graphical issues

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#237]
![untitled](https://user-images.githubusercontent.com/41223243/45821232-438ed180-bd1b-11e8-8857-455beb3d8023.png)
![untitled2](https://user-images.githubusercontent.com/41223243/45821233-438ed180-bd1b-11e8-8d9a-d972d0b0b767.png)

**Comment by barbudreadmon** [comment]
Fixed in the last commit
