### ISSUE TITLE
ASO - Armored Scrum Object (aso) flipped sprites

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#238]
![untitled](https://user-images.githubusercontent.com/41223243/45880036-3801e000-bdd9-11e8-9ac6-cdc66c406751.png)

**Comment by dinkc64** [comment]
barbudreadmon, fix on pm @ neosource :)

**Comment by dinkc64** [comment]
barbudreadmon, the fix is available on PM @ neosource :)

arnoldsecret, thanks for the report - after the fix is available make sure you go into the DIP's for this game and load the defaults.

**Comment by barbudreadmon** [comment]
Fixed in the last commit
