### ISSUE TITLE
twinhawk just boots to SERVICE SW ERROR

### ISSUE THREAD

**Issue by msheehan79** [libretro/fbalpha#239]
Not sure if this also occurs in upstream as I only have the libretro core installed, but with the current build  7c79ba9 this game loads but immediately displays "SERVICE SW ERROR" and won't start past that screen. 

Apologies if this is a known issue or if there is a common trick to get the game to boot beyond this screen. 

Confirmed the rom is the correct one using CLRmamepro. Also tested that the game loaded fine with MAME 201. Saw the same issue on Windows 10 x64 and a RPI3B (RetroPie).

**Comment by barbudreadmon** [comment]
Fixed, thanks for the report.

**Comment by AntiFly** [comment]
thanks , got same issue which related me to this post! great.
