### ISSUE TITLE
Run Ahead perf degradation over time

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/fbalpha#240]
When using Run Ahead, after a certain time of play the game will begin to slow down and sound to crackle when pushing buttons.

I was trying to find a way to make it easy to reproduce, leaving it on fast forward for a while but it doesn't seem to help.
I think it's happening as you're playing and calling states repeatedly via run ahead.

I had it happened (with the new save state fix from https://github.com/libretro/fbalpha/commit/7c79ba992cafa6e4cfb5519c67fec5f4b60cb990) playing Hyper Street Fighter II_ The Anniversary Edition (040202 Japan) with run ahead 2nd instance 3 frames reduction after around 20mn on a i5-3570k in gl with hard sync 0 frame enabled.

It was already happening before that commit, and also in 1 instance mode.
I did notice it in several games such as Battle Garegga near the end of the game (so probably a good 20mn+ as well).

**Comment by barbudreadmon** [comment]
How is cpu usage ?

**Comment by Tatsuya79** [comment]
I monitored it with MSI afterburner, that gave me a html log that is pretty useless outside of the program itself, anyway...

Playing Hyper Street Fighter II_ The Anniversary Edition (in the conditions mentioned earlier) it started to slow down after 30mn.
The graph shows that 1 core started with an average 35% usage that went up steadily overtime to 70% after 40mn.

RAM usage doesn't seem to have change much, but I monitored it globally for the OS.
At least no big leak it seems.

**Comment by Dwedit** [comment]
This needs profiling.  Profiling!  Only thing is I don't have a working installation of a suitable toolchain to build this program.  I do have a symbol converter though, so if someone could build it with full debug information and no symbols stripped, I could run it in the MSVC profiler.

**Comment by Tatsuya79** [comment]
[Here, I compiled it in mingw64 gcc 7.3 with DEBUG=1.](https://mega.nz/#!g1VxDa6J!BzSZLwvMmewdlFahmmbJUjUc7ip6DrO2HZ6uBXIUJOI)

**Comment by Dwedit** [comment]
CV2PDB took a decent amount of time to run on that dll...

Modified Retroarch to always resync state every frame, as if input was dirty, and running Twinkle Star Sprites with fast forward on.  Framerate starts out at around 170, and after a while tapers down to 64.8, will look at a profile log soon.
