### ISSUE TITLE
Missing pause button on CPS Changer games

### ISSUE THREAD

**Issue by litaniast** [libretro/fbalpha#245]
Street Fighter Zero and Warrior of Fate CPS Changer version have pause button per player, but currently can't use it in libretro.

For CPS Changer games, Pause + Start button combo is needed for access service mode.

**Comment by barbudreadmon** [comment]
@litaniast i didn't know about that, do you think "select" would be a good default button for this "pause" button ?

**Comment by barbudreadmon** [comment]
Fixed
