### ISSUE TITLE
CLRMame loaded .dat files not shown in CLRMame

### ISSUE THREAD

**Issue by AntiFly** [libretro/fbalpha#246]
HI, ive downloaded cmp4035_64 and the current .dat files ive found here.

Arcade is working fine but all other dat files wont show up in cmp4035_64.
do i something wrong or are the .dat files not the correct ones or bad???

i trie to check on the other sets.
like 
FB Alpha v0.2.97.43 (ClrMame Pro XML, ColecoVision only).dat
FB Alpha v0.2.97.43 (ClrMame Pro XML, Game Gear only).dat
etc...
help most appreciated.
thanks

**Comment by barbudreadmon** [comment]
> do i something wrong

Most likely, the dat files are working fine. 
Did you forget clicking on "NEW DATFILES" in the top left after adding your dat files ?

**Comment by AntiFly** [comment]
@barbudreadmon 
nope found the issue. ive rightclickdownloaded these from here https://github.com/libretro/fbalpha/find/master
and these is something xml web jnl code instead of the xml for the crcs... ... or i didnt realized how to really download the xml file here..
ive grabbed the code from raw now and changed the files to that... working now ;)

**Comment by barbudreadmon** [comment]
Ok, closing then
