### ISSUE TITLE
Old Rom -> renew CRC32

### ISSUE THREAD

**Issue by AntiFly** [libretro/fbalpha#247]
dat: FB Alpha v0.2.97.43 (ClrMame Pro XML, Megadrive only).dat

current:: rom name="shining tactics absolute final edition (hack).bin" size="4194304" crc="49d556e2"/
should be 
new:: rom name="shining tactics absolute final edition (hack).bin" size="...." crc="44d9b263"/

as for my understanding its related to http://www.romhacking.net/hacks/670/ which is nowadays (since 2016) v.1.0 but the crc32 does not match to yours. 
if this source is pointing to a (seems so to me) newer patch file as your implemented one ???

same on this core;
FB Alpha v0.2.97.43 (ClrMame Pro XML, Game Gear only).dat
the used translation is outdated. new date is 26.06.18 with v1.02 (i guess the old crc was from v1.01??)
on the vanilla one the crc should be then:
current:: rom name="megami tensei gaiden - last bible s (english translation).gg" size="524288" crc="8a44108b"/
new:: rom name="megami tensei gaiden - last bible s (english translation).gg" size="524288" crc="c9125c8a"/

https://www.romhacking.net/translations/3160/

can you check on that ?

**Comment by barbudreadmon** [comment]
Those translations (last version) were applied to clean No-Intro dump and tested with fbalpha. Closing.

**Comment by AntiFly** [comment]
> 
> 
> Those translations (last version) were applied to clean No-Intro dump and tested with fbalpha. Closing.
> 
> Edit : could be that the "megami tensei gaiden" version is outdated, however you can use the updated one, fbalpha doesn't fail on crc

shining tactics absolute final edition (hack).bin is definitly wrong crc, romhack point to the correct crc32 of the source file and if you would have been checked on that i think you would agree. so the avail translation does not match to the crc in .dat...
whatsoever my point was to help not to complain, i fixed it for me ....

**Comment by barbudreadmon** [comment]
> romhack point to the correct crc32 of the source file

@AntiFly Not true, sometimes it points to the crc of the source file, sometimes the result file. When i couldn't figure out where the crc came from (most likely from a old/bad dump), or if the rom with the expected crc wouldn't work (it happened too, i don't remember which ones), i decided to use the latest clean dump known to produce the translated version (if the result worked).

**Comment by AntiFly** [comment]
@barbudreadmon 
aha with your information about the no-intro i got it.
Shining Force II (USA).md from 2016 no-intro worked to that crc you point to.

hum ok whats the clue here..? where should people know which one was the source to your crc then ??
i mean there is no information which source did you worked with to create that particular rom with (at least none i would know of)

**Comment by barbudreadmon** [comment]
@AntiFly It appears you were wrong, as specified in the sources of fbalpha, http://www.romhacking.net/hacks/1736/ was used for this hack. And yes : 
- the hack was named "Shining Tactics Absolute Final Edition" at the time i applied it (same author as the other, seems to be the 2.0 version)
- the hack had updates since then (last one was 1 week ago), so the crc of the patched version in fbalpha won't match.

If i start updating crc every time there is an update, there will be no end to this. If you have a good source for your fba romsets, don't worry the files with the right crc will be in there after .44 is released.

**Comment by barbudreadmon** [comment]
@AntiFly They are present on a certain forum you know about...

**Comment by AntiFly** [comment]
@barbudreadmon 
most appreciated. i figured that out for every rom but those ones i was not able to "revert".
even with the romhack link from you im on the wrong crc, Im going nuts on that because i just want to make it myself ^^
anyway thanks for help
