### ISSUE TITLE
MD additions, Star Chaser no availablity

### ISSUE THREAD

**Issue by AntiFly** [libretro/fbalpha#248]
hi there,

i really appreciate the work you do.
but the addition you made to the MD Core
rom name="starchaser-20140705.bin" size="45632" crc="fadd25a3"/
this file was free to download from the "developer" but isnt available anymore at the mainsource (and i didnt saw it anywhere).
why this non common thing gets added if there is no availability at all ?

i just patch it out for "fix" me.
br

**Comment by barbudreadmon** [comment]
Avoid posting multiple issues to complain about roms you can't find, those roms exist. Closing.
