### ISSUE TITLE
Build now failing on Tinker under Armbian, undefined reference to `process_sinc_neon_asm'

### ISSUE THREAD

**Issue by EriHoss** [libretro/fbalpha#249]
Build fails with:

```
src/burner/libretro/libretro-common/audio/resampler/drivers/sinc_resampler.o: In function `resampler_sinc_process_neon':
sinc_resampler.c:(.text+0x6d4): undefined reference to `process_sinc_neon_asm'
collect2: error: ld returned 1 exit status
makefile.libretro:584: recipe for target 'fbalpha_libretro.so' failed
make: *** [fbalpha_libretro.so] Error 1
```

Built by RetroPie-Setup like this (optionless):

``make -f makefile.libretro``

Had not encountered this issue building about a week ago.

Build log: [rps_2018-10-09_055515.log](https://github.com/libretro/fbalpha/files/2459073/rps_2018-10-09_055515.log)

**Comment by barbudreadmon** [comment]
Depending if retropie is using one of the known platform or not to declare they are building for a neon architecture, perhaps they'll have to add `HAVE_NEON=1` to their build script.
