### ISSUE TITLE
Glitch on KOD rom (characters bar)

### ISSUE THREAD

**Issue by furiadeoso** [libretro/fbalpha#250]
Hi! There is an issue that I have long wanted to report. There's a glitch in The King of Dragons in multiplayer. 

Status /characters bar is flicking and is partially hided in two situations:
1. When choosing characters: (see 00:00:33 of my video stream)
2. When there is a transition (between stages) (see 00:02:07 of my video stream)

Video stream:
https://www.twitch.tv/videos/321325247

I have not had a chance to try it on standalone version.

Best regards.

**Comment by barbudreadmon** [comment]
@furiadeoso the fix was commited, let me know if the problem persists (it would mean it's related to netplay i guess ?)

**Comment by furiadeoso** [comment]
Thanks! This weekend I'm out. I'll take a look and comment again on Monday.

**Comment by furiadeoso** [comment]
Confirmed! It's solved. Thank you very much again.
