### ISSUE TITLE
[Feature Request]Please add custom assemby keys and turbo switch.

### ISSUE THREAD

**Issue by leoxxx** [libretro/fbalpha#253]
As the title.
For example.
Custom assemby keys:A game have "ABCD" keys. A actual key or virtual key can be remaped to any amount of these keys. Such as "AB", "CD", "ABC", "ABCD" and so on.
Turbo switch:A game have "ABCD" keys. A switch can control any keys turbo mode. On is turbo mode, off is normal mode. The switch for each key. Now RetroArch always push down the turbo key, then  push down key which you want to swtich turbo mode. It's different.

**Comment by barbudreadmon** [comment]
@leoxxx examples please, i have been searching for a core using this, or documentation, however i didn't find any. Actually that's something i have wanted for a long time (to remove the macro code from core options).
Perhaps @fr500 would know more ?

**Comment by leoxxx** [comment]
@barbudreadmon 
I can give you some emulators.
PC
FBAS: https://mega.nz/#!0Ul0yKwC!-QclZcJwl8_u3eJJwgup4FoKLkFWIYKZ-DegFXehQOE
Source Code: http://f.ppxclub.com/684707-1-1
https://mega.nz/#!gN1i3YgI!ku0grybmyfsrKuzCDtMhEd6Kd1Yt0iYb40nauTQ-h8g

Android
fba4droid: https://mega.nz/#!lQ11SCTb!E1PRRUshgSMdHlcmnmQzqX9DPpkEj4QFucEIkAqA7hg
kawaks: https://mega.nz/#!lAkHBaKR!DPgYQaa0RaWIX7IhW4qCYARCktNKxB47pXaGQTtc4zs

**Comment by barbudreadmon** [comment]
Can't do that, i thought you were talking about libretro feature, closing.

**Comment by fr500** [comment]
Combos should be a frontend feature in input_remapper.c
The input mapper already knows how to "overwrite input"

So what's needed is the combo logic, and the gui to create the combos

**Comment by leoxxx** [comment]
@fr500 
But I found custom assemby keys in some rom's option.
For example, kov(Knights of Valour).
