### ISSUE TITLE
Thunder Ceptor (tceptor, tceptor2) - cannot move

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#33]
Only firing works in these games.

**Comment by barbudreadmon** [comment]
This one is kinda tricky, it's played with 3 analog controls (the 3rd one being the accelerator) + 4 fire buttons. The easiest way to deal with it might be to map X/Y axis to retropad left analog, and accelerator to retropad right analog, however using retropad right analog would make using B/A/Y/X as fire buttons kinda unintuitive, another option would be to map accelerator to analog R2 button then.

@arnoldsecret What do you think ?

**Comment by arnoldsecret** [comment]
it's alright

**Comment by barbudreadmon** [comment]
There is an issue with accelerator, not sure if i'm doing something wrong or if it's not working in standalone either. I'll check when i have some time.
