### ISSUE TITLE
Sonic Boom (sonicbom) - orientation flipped 

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#34]
![50043612-81995880-00b2-11e9-88ff-79f941b54f66](https://user-images.githubusercontent.com/41223243/50048127-3a858480-00ff-11e9-966e-48ea90dad23e.png)
According to barry65536, this port needs the BDF_ORIENTATION_FLIPPED flag to display the correct orientation.

**Comment by barbudreadmon** [comment]
> According to barry65536, this port needs the BDF_ORIENTATION_FLIPPED flag to display the correct orientation.

We already do that though, i'll investigate

**Comment by barbudreadmon** [comment]
Looks to me like you were right in posting this issue upstream. I applied a fix and let them know about it.

**Comment by barbudreadmon** [comment]
Reverted my commit, it's not a proper fix actually (there are some graphical issues when doing this), i'll be waiting for the proper fix from upstream.
