### ISSUE TITLE
[PCE/SGX/TG16] Scaling issue

### ISSUE THREAD

**Issue by retro-wertz** [libretro/fbalpha#36]
![screenshot_2018-12-16_20-26-51](https://user-images.githubusercontent.com/23315382/50053497-31cd9680-0171-11e9-9821-e09432bd9356.png)

**Comment by retro-wertz** [comment]
false alarm. got set apsect to PAR (scaling should probably not be available for console imho other than the ra provided one)

**Comment by barbudreadmon** [comment]
Now i force all home console systems to PAR, let me know if it's causing issues with some of them

**Comment by retro-wertz** [comment]
should have been DAR... PAR was whats causing image to shrink or scale in 512x240 px

**Comment by barbudreadmon** [comment]
Ok, i thought it was some issue with the default DAR value, i reverted the commit.

More details about those 2 settings : 
- DAR will set the ratio coded in fbalpha for the game
- PAR won't set this ratio (so i guess RA will use width/height to determine it ?)

I'm not 100% sure why the PAR setting exist, @AkimanBengus might be able to tell us more about it ? I'm pretty sure he added this code.
