### ISSUE TITLE
Vindicators descriptors 

### ISSUE THREAD

**Issue by alfrix** [libretro/fbalpha#37]
Vindicators I 
Currently the button that fires is described as `left stick thumb` should be `right stick fire`
and `right stick fire` is `left stick thumb`

Vindicators II
Button 1 is > left stick fire
Button 2 is > left stick thumb
Button 3 is > right stick fire
Button 4 is > right stick thumb

**Comment by barbudreadmon** [comment]
Thanks, fixed :)
