### ISSUE TITLE
Battle Cruise M-12 freezing

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/fbalpha#44]
Romset name : bcruzm12
Test platform : libretro linux x64

Stuck on this screen at launch : 
![bcruzm12-181220-081814](https://user-images.githubusercontent.com/10391265/50269923-32478500-0430-11e9-9c5a-1cdb9e6072f0.png)
Framerate keeps going on so it's not really a freeze.

No asan/ubsan error, no dip issue either.

Confirmation of the issue in standalone needed

**Comment by retro-wertz** [comment]
this does run after a few seconds if you just leave it alone though...
![screenshot_2018-12-21_19-51-04](https://user-images.githubusercontent.com/23315382/50341451-d416c100-0559-11e9-876f-89b58a49a583.png)

**Comment by barbudreadmon** [comment]
Ok, it seems i didn't wait enough (~15 seconds), closing then :)
