### ISSUE TITLE
krzybowl, capbowl - glitchy trackball controls

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#49]
krzybowl - ball moves northwest on its own

capbowl - remapping trackball to d-pad glitches the controls

**Comment by dinkc64** [comment]
Thanks for the bug report!
trackball can't be mapped to d-pad unless it has up/down/left/right options. 
I agree, krzybowl and capbowl are my first attempts to get trackball working and they need to be updated to the latest device.  I will try to get this done soon :)

**Comment by arnoldsecret** [comment]
I remapped the trackball to use d-pad manually through the libretro control options

**Comment by barbudreadmon** [comment]
@arnoldsecret i did the same and didn't have any issue, what's happening exactly ?

**Comment by arnoldsecret** [comment]
while I'm trying to make a remap file for capbowl I came across another issue, the coin button plays a noise when I remap the trackball to dpad.
here's the remap file.

> input_libretro_device_p1 = "1"
input_libretro_device_p2 = "1"
input_libretro_device_p3 = "1"
input_libretro_device_p4 = "1"
input_libretro_device_p5 = "1"
input_player1_analog_dpad_mode = "1"
input_player1_btn_down = "18"
input_player1_btn_left = "17"
input_player1_btn_right = "16"
input_player1_btn_up = "19"
input_player2_analog_dpad_mode = "0"
input_player3_analog_dpad_mode = "0"
input_player4_analog_dpad_mode = "0"
input_player5_analog_dpad_mode = "0"

**Comment by barbudreadmon** [comment]
> input_player1_analog_dpad_mode = "1"
input_player1_btn_down = "18"
input_player1_btn_left = "17"
input_player1_btn_right = "16"
input_player1_btn_up = "19"

@arnoldsecret Don't use `analog_dpad_mode` if you are already remapping buttons individually ?

**Comment by barbudreadmon** [comment]
Ok, i'll close then (krzybowl controls were fixed in https://github.com/libretro/fbalpha/commit/247ddb829c590b5ceeb8a5439c23a28c07f01bfb)
