### ISSUE TITLE
Certain games won't recognize input #36

### ISSUE THREAD

**Issue by Oggom** [libretro/fbalpha#5]
The controls in Quartet (quartet.zip) are not recognized despite being mapped out properly rendering the game unplayable. The 2-player version (quartet2.zip) is not affected by this.
Angel Kids (angelkds.zip) and Bullet (bullet.zip) are also having similar issues.
https://github.com/libretro/fba-libretro/issues/36

**Comment by neilmunday** [comment]
I have also found that bdash.zip, frogger.zip, frogger2.zip do not respond to control pad input or keyboard input regardless of setting gamepad/arcade mode in the core options. Is this a bug?

**Comment by barbudreadmon** [comment]
I need to check libretro.cpp and coleco driver to see if bindings are ok.

**Comment by barbudreadmon** [comment]
They are not, but i don't really know how i should map it, that's a 16-button controller with a numeric keypad... Any suggestion ?

**Comment by neilmunday** [comment]
That is a tough one. From the Wikipedia pages, the ColecoVision controller accepted different overlays for the numeric keypad for different games to map the buttons. This would explain the differences in joystick behaviour between games.

From looking around the web, it's a common problem with ColecoVision emulators. From the few games I have tried, "#" on the ColecoVision joystick seems to be used as the start button if that helps.

Are all available RetroArch joystick buttons mapped or are there some free (e.g. L2, R2 etc.) that could be mapped to some buttons? The more buttons that can be mapped hopefully the fewer games that will be unplayable with a control pad.

Is it also possible to map a keyboard's number pad to the equivalent inputs for the ColecoVision numeric keys?

**Comment by barbudreadmon** [comment]
quartet, angelkds, bullet should be fixed, i still don't know how to handle coleco games (14 buttons, retropad has at most 12 buttons, and i'm including start, select, R3 and L3)

**Comment by barbudreadmon** [comment]
I close this one, let's keep all input issues in the same place : #102
