### ISSUE TITLE
[GNU/Linux] Building a version with selected drivers

### ISSUE THREAD

**Issue by vanfanel** [libretro/fbalpha#54]
Hi there!

I rebuild and update the libretro cores frequently for my Pi3 and my friends and family different Pi models, so I usually remove some drivers from FBAlpha in order to speed up building on Pi2 for example.
It used to be very easy: I just had to remove the directories from the 'generate-files' from makefile.libretro, and the directory lines from 'FBA_BURN_DIRS :=' in makefile.libretro_common, then I had to run 'make genarate-files' and... presto! I could build an fbalpha core with selected drivers.

Now I can't do it because I can't see a way to remove drivers in makefile.libretro, and if I only remove the dir lines in makefile.libretro_common and run 'make generate-files' it fauls to build...
Can you please point me to the right way to remove drivers with the current codebase, please?

**Comment by barbudreadmon** [comment]
Normally you can remove the ones you don't need in : https://github.com/libretro/fbalpha/blob/ad6dd2ea56f5f170ac709be2836298535d863324/makefile.libretro_common#L124-L149

**Comment by vanfanel** [comment]
@barbudreadmon : It seems I was doing something wrong, it's as easy as you say!
Sorry, closing this up.
