### ISSUE TITLE
[GNU/Linux aarch64] Cyclone CPU build fails 

### ISSUE THREAD

**Issue by vanfanel** [libretro/fbalpha#56]
HI there,

Since I have a Rpi3 running in aarch64 mode, I am trying to build with a new platform definition that goes like this:
```

  else ifneq (,$(findstring rpi3_64,$(platform)))
      PLATFORM_DEFINES := -march=armv8-a+crc -mtune=cortex-a53
      USE_CYCLONE = 1
   endif
```

However, the cyclone asm fails building, so I have do disable the USE_CYCLONE=1 to build on aarch64. Since aarch64 is becoming common in GNU/Linux devices, maybe it would be good to have it working?

Thanks!

**Comment by barbudreadmon** [comment]
@vanfanel not happening, cyclone is arm32 only, and pointless on rpi3 anyway

**Comment by vanfanel** [comment]
@barbudreadmon : Oh, I see. I have been measuring CPU usage on the Pi3 and it's low anyway. Thanks for taking the time to answer :+1:

**Comment by barbudreadmon** [comment]
@vanfanel Cyclone only affects games using a m68k cpu, and i don't know any m68k game that would run poorly on a rpi3. Since using cyclone is breaking savestates compatibility with other arch it's not something you want to do for no gain.
On a sidenote, i wouldn't recommend installing an aarch64 system on any arm board for retrogaming purpose, many emulators only have arm32 dynarecs and will perform like shit on aarch64 if the cpu frequency is not high enough to counterbalance the loss of the dynarec.

**Comment by vanfanel** [comment]
@barbudreadmon : You made good points all around, yes. But my usercase is a bit different: I don't use any cores with dynarecs (not interested in inaccurate PCSX emulation, or choppy ARM-based N64/DC emulation) but only 8 & 16 bit emulators like the fantastic FBAlpha for arcade, Nestopia. GenesisPlusGX and SNES9x, along with native cores like TyrQuake, NXEngine and Dinothawr.
So, all in all, I get a BIG performance boost going aarch64. In arm32 mode, the Pi3b+ is unable to cope with some SNES games using the SNES9x core (not the hacky 200x versions, but SNES9x baseline core) when using VC4 + max_swapchains=2, but the same Pi3b+ has no problems emulating every SNES game (excluding SuperFX and SA-1, of course) on the same low-latency conditions if I use an aarch64 system.
It doesn't seem to be common knowledge because of the lazy people at the Rpi foundation only produce 32bit debian-derivatives, but a Pi3/3b+ on armv8 mode (aarch64) is WAY faster for emulation than running in armv7 mode (arm32).

So, it's aarch64 for me all the way. And someone's gotta test the way to aarch64 anyway! We are all going there someday sooner or later :D

**Comment by barbudreadmon** [comment]
> So, all in all, I get a BIG performance boost going aarch64. In arm32 mode, the Pi3b+ is unable to cope with some SNES games using the SNES9x core (not the hacky 200x versions, but SNES9x baseline core) when using VC4 + max_swapchains=2, but the same Pi3b+ has no problems emulating every SNES game (excluding SuperFX and SA-1, of course) on the same low-latency conditions if I use an aarch64 system.

I'm surprised by this statement, apart from very specific cases (like emulating another 64bits machine), 64bits shouldn't be faster than 32bits for emulation (in most case, although only marginally, it is the other way around). Maybe there is an issue in the 32bits OS you were using, or in the core itself ?

In fbalpha on a aarch64 rpi3b+ (at normal clock), do you get full speed in games like svg or rtypeleo ? On my arm32 rpi3b+ i've to OC it a bit (1450Mhz iirc).

**Comment by vanfanel** [comment]
@barbudreadmon : I am surprised myself too. There shouldn't be a difference. But there IS, I tell you for sure. It wasn't my 32bit OS: I build my own OS from kernel sources, manually install an aarch64 or arm32 rootfs and if there's a service running there it's because I put it there, so I know what's on my system and nothing was using up any of my cores in arm32 mode. 

I will do a full FBAlpha build and test rtype LEO on aarch64 on the pi3b+. Will come back with the results.

**Comment by vanfanel** [comment]
@barbudreadmon : R-type Leo isn't fullspeed on the PI3b+ in aarch64 system+FBAlpha. It's almost there, but not fullspeed. Note I tested with max_swapchain=2.
