### ISSUE TITLE
Analog control input issues

### ISSUE THREAD

**Issue by Oggom** [libretro/fbalpha#6]
The libretro port of FBA doesn't seem to handle analog controls properly at the moment despite them being mapped out properly, rendering some games unplayable.
Examples are After Burner, Rambo III and Forgotten Worlds
https://github.com/libretro/fba-libretro/issues/37

**Comment by barbudreadmon** [comment]
Interesting fact : bbusters, which uses analog for his light gun, works

**Comment by barbudreadmon** [comment]
Fixed

**Comment by Oggom** [comment]
Thanks
