### ISSUE TITLE
Request to restore (m107. cpp and m92. cpp) Spssed Hacks function?

### ISSUE THREAD

**Issue by ji125443** [libretro/fbalpha#63]
Because on ARM, Amlogic s905 platform is very important

![screenshot_2019-01-01-08-39-13](https://user-images.githubusercontent.com/25021120/50569540-4d0be900-0da2-11e9-8328-cf7dd75d7bc5.png)

**Comment by barbudreadmon** [comment]
This hack was removed because there was no fps gain, i have no intention to add it back. You can try the frameskip option instead, it works way better.
