### ISSUE TITLE
NeoGeo saves don't work after restarting the core & misc save issues

### ISSUE THREAD

**Issue by fr500** [libretro/fbalpha#76]
If you save a neogeo save it works fine, until you close the core, then it loads the state and locks up.
CPS seems to work fine though.

There are several hacks inside this core, I added a few instead of going thru the correct interfaces.
For instance, I added back the standalone FBA saving routines for nvram (it saves .fs files for neogeo, .nv files for CPS2/3)

Instead we should go thru the correct libretro interface.

Save states are really volatile with this core.
Here are my test results:

Xmen vs. SF CPS2 / ACB_FULLSCAN
- works fine if you save and load in the same session, sometimes the music slows down, missing instruments till a character/round change, game works
- loads fine if you load in another session but music is totally garbled till a character/round change
- bios settings save correctly with my hacked method

Garou NeoGeo / ACB_FULLSCAN
- works fine if you save and load in the same session, sometimes the music is somewhat garbled and random sfx play back, missing instruments till a round change, game works
- loads fine if you load in another session AFTER the BIOS sometimes the music is somewhat garbled and random sfx play back
- game hangs if you load in another session BEFORE the BIOS finishes running
- bios settings save correctly with my hacked method

SFIII3 CPS3 / ACB_FULLSCAN
- works fine if you save and load in the same session, sometimes the music is somewhat garbled and random sfx play back, missing instruments till a round change, game works
- crashes if load a state in another session
- bios settings save correctly with my hacked method

**Comment by fr500** [comment]
Xmen vs. SF CPS2 / ACB_VOLATILE

-    works fine if you save and load in the same session, sometimes the music slows down, missing instruments till a character/round change, game works
    loads fine if you load in another session but music is totally garbled till a character/round change
    bios settings save correctly with my hacked method

**Comment by fr500** [comment]
We should try to model the way we save / load states after standalone, it looks quite different at least.

**Comment by TheElf01** [comment]
Hi, I think all games have savestates problem, just bigger the rom, much chances to have glitches

Try for example Sailor Moon, is almost impossible not to load a state without glitches. If you do after bios loading, less chances to fail anyways

CPS1 is affected too,  tried some games, like Captain Commando, and fail too

**Comment by blackman91** [comment]
I can confirm this bug happens also on Android using the same core.
