### ISSUE TITLE
[BUG] [0.2.97.38] [RPI2] non working games 

### ISSUE THREAD

**Issue by nemo93** [libretro/fbalpha#79]
I've updated my Retropie to the latest revision and so to the latest lr-fba (0.2.97.38). I also seized this opportunity to clean my romset and I now got a complete 0.2.97.38 romset, perfectly clean set. And I'm enjoying it!!! Yet I got issues with the 2 following games (I'm already aware of the issue with Irem's games):

* macross.zip
* raiden2.zip (same with raiden2dx.zip)

Both refuse to launch, libretro simply doesn't start at all like the when roms are not ok but I'm sure about my romset :) 

I'm running a RPi2, Retropie 4.0-beta3. Unfortunately I see nothing in logs and I'm not even sure where to have a look at. Let me know what else do you need and I'll get you that. 

Thanks a lot!

**Comment by barbudreadmon** [comment]
all raiden games use same nec v30 cpu as Irem m72/m92/m107 games, they don't work on arm, i spent countless hours trying to figure out why but no clues.
I didn't know about macross, i'll take a look when i've got time, m68k/z80 games should work.

**Comment by barbudreadmon** [comment]
Raiden games are part of https://github.com/libretro/fbalpha/issues/9
Macross issue got solved by latest commits.
I close since this issue is now only a duplicate
