### ISSUE TITLE
Ultra balloon second player controls not working

### ISSUE THREAD

**Issue by furiadeoso** [libretro/fbalpha#79]
Ultra balloon (UBALLOON) seems to have something bad with player 2 controls. We have detected in netplay than player 2 controls are not working at all, but also I've tried to use player 2 controls in offline mode and I can't insert coin or press start. 
I don't see any related option in Dip Switches.

Regards.

**Comment by dinkc64** [comment]
Will have a fix tomorrow, thanks for the report!

**Comment by dinkc64** [comment]
Fix is in the main repo, thanks again for the bug report :)

**Comment by furiadeoso** [comment]
Thanks you too! I try to help in what I can :)
