### ISSUE TITLE
[BUG] [0.2.97.38] [Windows x64] Can't insert coin in Space Invaders (invaders.zip)

### ISSUE THREAD

**Issue by iosadosd-quarto** [libretro/fbalpha#81]
When trying to play Space Invaders, I can't insert coin using the "Select" button (on the RetroPad abstraction) like I do for any other game, and then as soon as the game's first screen (the Score tab) has finished and the gameplay demo starts, RetroArch crashes. On the log I see that the Coin input is "unaccounted".

Does anyone know can I fix this? It's somewhat ironic that among all the arcade games in existence, I can't play probably the most influential one!

[log.txt](https://github.com/libretro/fbalpha/files/420790/log.txt)

**Comment by dankcushions** [comment]
what (if anything) is your hotkey? could be this issue: https://github.com/libretro/fbalpha/issues/44

**Comment by iosadosd-quarto** [comment]
I usually play with a X360 controller, and my hotkey is the Home button, while the "Insert coin" is Back. When on a keyboard, my hotkey is f5 and "Insert coin" is RShift.

The weird thing is that I encountered this bug only on Space Invaders (for now, at least). Every other game recognize the "Insert coin" key just fine (Mario Bros, Metal Slug, Donkey Kong...)!

**Comment by barbudreadmon** [comment]
I confirm this issue

**Comment by barbudreadmon** [comment]
Should be solved, i close.

**Comment by iosadosd-quarto** [comment]
I hope so, now I'll just wait for the new version of the core to come out :smile:
