### ISSUE TITLE
(kof10thd.zip) is it supported?

### ISSUE THREAD

**Issue by ji125443** [libretro/fbalpha#81]
If not, request that support be added！

**Comment by barbudreadmon** [comment]
1. I'm pretty sure it's not the first time you ask
2. I'm pretty sure i already answered
3. We don't take request

Maybe i'll look at this, maybe not, in both cases i'm closing this issue.

**Comment by barbudreadmon** [comment]
Oh, and btw, if you really want this support, you can also try implementing it yourself, in best case scenario it's not actually hard : https://github.com/libretro/fbalpha/commit/d8edfdd6187d491c313c69b7061231555223e386

**Comment by barbudreadmon** [comment]
I have been writing some guiding lines on how to add romset from hbmame to fba (#122). In the case of kof10thd it was extremely straightforward, you should have tried. Anyway this hack is now supported.
