### ISSUE TITLE
[BACKPORT REQUEST] AkimanBengus, can you port your dipswitches codes to fbalpha_2012?

### ISSUE THREAD

**Issue by GanXiaobing** [libretro/fbalpha#82]
The efficency of FBA 0.2.97.38 decreases a lot comparing to FBA 0.2.97.30 or earlier releases. It performs terrilbe on less powerful platforms such as Wii, Raspberry 2. So, AkimanBengus,as the contributor  of dipswitches codes,  can you port your codes to fbalpha_2012, fbalpha2012_neogeo, fbalpha2012_cps and fbalpha2012_cps2? That would help a lot. Thank you in advance.

**Comment by barbudreadmon** [comment]
Your raspberry 2 have issues if current fbalpha performs terrible on it. By the way, what's the bottleneck with fbalpha on wii ? ram only ?

**Comment by barbudreadmon** [comment]
btw, if you don't write something like @AkimanBengus , he'll probably never see this issue.

**Comment by AkimanBengus** [comment]
Hello,
I was on holiday these last few weeks.
I don't know if it will be easy to port this code because I don't know how much different they are.
And unfortunately, I haven't many times for now :-(

**Comment by barbudreadmon** [comment]
@AkimanBengus : libretro implementation in fbalpha2012 should be this one from 2 years ago, rewritten in pure C.

**Comment by barbudreadmon** [comment]
@GanXiaobing : 
Following the discussion on fba forums : 
What are you talking about with ssriders ?
I ran this game on both cores, without any overclocking, i even went further : i underclocked my raspberry at 600Mhz, which is around half his real speed, and i was transfering my new fba romset to my raspberry at the same time. You know what ? I had the same speed on both cores, which means full speed.
Then i checked the sources related to ssriders, yes there were changes, notably on m68k which ran horribly for some games on fbalpha-libretro 0.2.97.24 (altered beast ?), but nothing i could consider a breaking change on speed.
There is something wrong with your raspberry, i can't tell if it's your distro, your raspberry itself, or your settings, at this level it's probably all of them.
If you are using a raspbian based distro, it confirms what i've been thinking (and saying) for 2 years : raspbian is **BAD** for performance on raspberry pi 2/3.
Stop asking for backports : **FIX YOUR RASPBERRY**.
I close...
