### ISSUE TITLE
[Rpi3] CPS1,2,3 fails to boot

### ISSUE THREAD

**Issue by LodanZark** [libretro/fbalpha#83]
After updating this core from the source, the games related wtih CPS1,2,3 fails to load, I am wonder if this issue its connected with the latest commits

**Comment by barbudreadmon** [comment]
What's the retroarch output ? No error message ?

**Comment by LodanZark** [comment]
Sorry the misleading, the emulator was renamed "fba_libretro.so" to "fbalpha_libretro.so" and I didn't update the config file, It is working fine.
