### ISSUE TITLE
[Request] Lightgun support

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#83]
Maybe an aiming reticule similar to the one found in the desmume core?

**Comment by barbudreadmon** [comment]
Idk how this stuff works, i'll ask the libretro team for information.

**Comment by barbudreadmon** [comment]
It doesn't seem to me like it's possible to implement right now : the lightgun RA device provide direct coordinates, however the fbalpha input system expect "movements", maybe @dinkc64 would know if it's somehow possible to do something about this ?

**Comment by dinkc64** [comment]
I will have to think about this for a while to come up with something... hmmm..

**Comment by dinkc64** [comment]
Theoretical idea stuff (for later) / aka just thinking out-loud here to try to get ideas:

It would involve tagging each lightgun-capable game with something like BDF_LIGHTGUN, and making an interface into burn_gun to push in the coords from the lightgun.  I would agree to make the initial code and hook up a game or 2, but I would need help doing this to every other game that is capable.
-or-
even better idea, I could make a burn_gun callback that can be setup whenever a lightgun is in use, and even if the game isn't a lightgun game, it would not cause any problems to call this callback thing - that way all lightgun games can be hooked up to it across the board without tagging them.

**Comment by barbudreadmon** [comment]
The second idea seems more convenient indeed.

**Comment by dinkc64** [comment]
barbudreadmon,
I added BurnGunSetCoords(player, x, y); to the burn_gun interface.
Also BurnGunIsActive() will return !0 if a gun is active for the game.  Check this after calling the drvinit to see if you need to enable the gun or not.

For testing, edit burn_gun.cpp and change "bool bBurnGunAutoHide = 1;" to "bool bBurnGunAutoHide = 0;", when you're happy with how it works, change it back (if you want) :)

The gun interface can take 2 different types of coordinates:
0-255 for x and 0-255 for y, regardless of the games' resolution
or
let's say a game is 384x by 224y
the x param can be 0 to 384-1 and y can be 0 to 224-1.  This is the method I set BurnGunSetCoords() to accept, if you need to change it to the 0 to 255 method, comment out the 2 lines in the function and uncomment the 2 lines above.  I'm not sure what kinda output the libretro lightgun device has..

Good luck, I think that's all you'll need for impl. :)

**Comment by barbudreadmon** [comment]
Thanks :), i'll try to test/implement this today/tomorrow

**Comment by arnoldsecret** [comment]
just tested the gun controls, it works well except that the cursor moves slightly when idle after moving it.

**Comment by furiadeoso** [comment]
> just tested the gun controls, it works well except that the cursor moves slightly when idle after moving it.
Hi!
What kind of control are you using? A Dolphin bar?
Regards.

**Comment by barbudreadmon** [comment]
@arnoldsecret i didn't implement the libretro lightgun support yet (i took a look but it was trickier than i though to insert this in the current code, i intend to work on it this week-end), you are probably using something else (maybe your gun is recognized as a mouse or something like this)

**Comment by arnoldsecret** [comment]
I use PS4 DualShock 4 controller.

**Comment by furiadeoso** [comment]
Hum.... How can a ps4 controller be used as a lightgun? AFAIK It can be used as a mouse, but it can't get coordinates.

**Comment by arnoldsecret** [comment]
Left analog acts as the cursor.

**Comment by furiadeoso** [comment]
Ok. But cursor is like a mouse, not like a lightgun.

**Comment by arnoldsecret** [comment]
been trying out the lightgun feature for hours, did come across some issues in certain games though.
Examples:
gollygho - cursor doesn't move
lghost - Gun Adjust Error
targeth - player 2 hooked up, player 1 not hooked up

**Comment by barbudreadmon** [comment]
@arnoldsecret i'm not sure what you mean by lightgun feature, i didn't implemented it yet.

**Comment by arnoldsecret** [comment]
so Gunbuster got added, any chance of support on libretro?

**Comment by barbudreadmon** [comment]
@arnoldsecret Ok, now i understand your issue, you weren't asking about lightgun support, you were asking about lightgun games where my algorythm fails to bind all controls to the retropad.
I'll take a look at the games you mentioned this week to fix their controls with retropad, i'll also try to implement proper lightgun support. On a sidenote those games might have working controls if you set mouse as device type in `quick menu > controls`

**Comment by barbudreadmon** [comment]
1. I fixed controls for `gunbustr` and `targethr`. Now my algorythm shouldn't fail to bind anymore for those kind of controls
2. For lghost it's normal, you need to follow the game instructions to set the gun.
3. gollygho controls are probably broken

There is still no proper libretro lightgun support though, maybe tomorrow if i find some time.

**Comment by barbudreadmon** [comment]
I've no lightgun so i can't test, but i think it might be working now.

**Comment by barbudreadmon** [comment]
Both gun games mapping issues and lightgun/pointer device support should be ok, i'll close.
