### ISSUE TITLE
[SOLVED] Make dip switch or service mode available for all CPS games

### ISSUE THREAD

**Issue by bbhenry** [libretro/fbalpha#84]
I am using the latest recalbox beta and with fbalpha I don't see service mode options available for all the CPS games. I was able to see it for Captain Commando but not **Battle Circuit**. I have tried so many ways to try to bring out the service mode under fbalpha but no luck. 

So just to verify, I use mame2003 on recalbox to play Battle Circuit and there I was able to enter the service mode and enable 4 player games. Can we do the same under fbalpha?

![image](https://cloud.githubusercontent.com/assets/667944/17795178/f6d64634-656a-11e6-9a9e-97f64d40d0b3.png)
![image](https://cloud.githubusercontent.com/assets/667944/17795181/fe95d678-656a-11e6-9c4f-a1cc3621abf9.png)

**Comment by barbudreadmon** [comment]
Yes you can ! Setup "diagnostic input" in core options, then use this input while ingame to access the diagnostic menu

**Comment by barbudreadmon** [comment]
A confirmation would have been nice, anyway i close since it should be solved.

**Comment by AkimanBengus** [comment]
I have tested and I can enter the service mode in Battle Circuit using the combo input for diagnostic menu.
So there is no issue :-)

**Comment by bbhenry** [comment]
@barbudreadmon sorry I didn't see your reply until now. I will test. Thanks.
