### ISSUE TITLE
[0.2.97.38] [RPI2] regression - games that worked before

### ISSUE THREAD

**Issue by nemo93** [libretro/fbalpha#87]
I'm using Retropie (updated to latest version 4.0.1) and it comes with the latest Retroarch (keep me honest here). Before that the following games worked flawlessly:

* dragnblz (Dragon Blaze)

Now whenever I launch the game well it launches but the screen is like distorted or extended. Plus there's garbage on the screen making it unplayable. 

I should do further testing as I may have seen issue with Neo Geo as well (not confirmed yet).

**Comment by barbudreadmon** [comment]
Your last retropie version was ? Last possible changes on graphic rendering in this core was the v0.2.97.38 release in april (and i'm pretty sure there wasn't), so except if you did no update on your rpi for the last 5 months, i'm pretty sure your issue is a setup issue.

**Comment by barbudreadmon** [comment]
I confirm this issue, what's your previous retropie/fba version ?

**Comment by barbudreadmon** [comment]
Seems like https://github.com/libretro/fbalpha/tree/a71055b20efaa582d3af09d5aeba1d9bdf4ff1e8 was at fault, i remember seeing those changes in one of the fbalpha2012 cores at the time, it seemed like a good idea and less cpu intensive, it seems i was wrong. FIXED !
