### ISSUE TITLE
Violence Fight  P2 does not have mapped button 3

### ISSUE THREAD

**Issue by furiadeoso** [libretro/fbalpha#88]
In Violence Fight (world) viofight.zip and maybe clones (not tested),  P2 does not have mapped the button 3.

Confirmed also in .43 standalone version.

Regards.

**Comment by dinkc64** [comment]
furiadeoso, thanks for the bug report!  fix checked in :)

**Comment by furiadeoso** [comment]
Confirmed. Thanks!
