### ISSUE TITLE
[RPI2] IREM- Blank screen loading rtype 1-2-leo

### ISSUE THREAD

**Issue by amigagamer** [libretro/fbalpha#9]
As title states, im just getting a black screen when trying to load rtype games. Tested on a raspberry pi 2. 
 Rom verified working fine on standalone win32 FBA 029734.

Worth noting i have the same issue on libretro 029730 build from the older fba-libretro repository on rpi2, so its not specific just to this port.

**Comment by barbudreadmon** [comment]
Seems to be arch specific, r-types work fine on linux x86_64. Konami and irem issues could be the same kind i had with sms driver so i'll get a look this week-end.

**Comment by barbudreadmon** [comment]
@amigagamer, @Speedvicio, @nemo93 and whoever else asked about this issue : 
IREM games (and other games based on the same NEC cpu) should finally be fixed on raspberry :). It was a really dumb bug, caused by what seems to be a fix for a really dump Operating System.

**Comment by amigagamer** [comment]
Many Thanks barbudreadmon . All 3 rtypes tested and working on rpi3 via retropie.  Performance is slow on rtype leo due to 100% cpu usage but rtype 1+2 seem playable.

**Comment by barbudreadmon** [comment]
rtypeleo seems to be running fine on my overclocked rpi3 (but i'm not using retropie), here is my config.txt : 

dtparam=audio=on
dtparam=watchdog=on
dtoverlay=sdhost,overclock_50=84
arm_freq=1350
gpu_freq=550
over_voltage=5
sdram_freq=550
sdram_schmoo=0x02000020
over_voltage_sdram_p=6
over_voltage_sdram_i=4
over_voltage_sdram_c=4
gpu_mem=384
disable_splash=1

**Comment by amigagamer** [comment]
Works fine with the overclock (i was testing at standard speeds)
Discovered today R-Type 2 crashes consistently at the first indoor section (about 60 seconds into level 1) but only on retropie. A manual build on raspbian runs fine.

Looking at the compiler output on retropie it appears to be passing the retropie cflags AND the makefile specific flags (so we get -O3 as well as -O2 in the build line) May be caused by 03 building - referencing  https://github.com/libretro/fbalpha/commit/cd04ce06635c46146863c1f718ffe2c2c56a3ea2 
or one of the other cflags inherited from the retropie script. 
@joolswills FYI

**Comment by joolswills** [comment]
Thanks - I think I will put our default optimisation flags back to O2. Never noticed any improved performance, and it seems to introduce bugs - in other cases too.

**Comment by barbudreadmon** [comment]
I have been using the following for my whole system (Gentoo) on my rpi3 since it came out : 
`CFLAGS="-O2 -pipe -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations"`
I never had any issues with it, and i heard gcc won't produce neon-optimized code without "-funsafe-math-optimizations"
