### ISSUE TITLE
Bug, black screen of doom.

### ISSUE THREAD

**Issue by Razoola** [libretro/fbalpha#95]
It appears the lb/fba goes into a black screen of doom if a NeoGeo bios is used that has a crc mismatch.

To reproduce problem set 'Neo Geo mode' to DIPSWITCH, choose 'Universe Bios ver. 3.2', in neogeo.zip change one byte in uni-bios_3_2.rom to give a crc32 mismatch (say 0x80 to 0xFFFE which is a non critical change). Then reset/restart game.

A related situation: When 'Neo Geo Mode' is set to UNIBIOS. If a crc32 mismatch exists in unibios v3.2 (in neogeo.zip) the UI will force the next highest version unibios to be used instead of the crc32 mismatched version. 

The original PC finalburn and MAME allow loading of bios with a crc mismatch.

**Comment by barbudreadmon** [comment]
Yes, fba-libretro is not lax about bios's crc32. But is there a point in creating a crc32 mismatch on purpose ?
Doesn't look like a bug to me, at most it could become an improvement if there is a real purpose in doing this.

**Comment by Razoola** [comment]
Some users do this because their personal Universe Bios will have a unique crc32 and they may want to use it in emulation. Some users probably simply compile their own build after altering the crc, for other this may be to advanced for them to do (which is how the issue had come to my attention). Each unibios build is unique you see, even if it is of the same revision number of one known to the emulator.

Allowing a crc32 mismatched unibios to load would help those users, even if the exception is only allowed for in the lastest unibios version known to the emulator. At this time that would be 'uni-bios_3_2.rom'.  I do however see the other side of why there are strict rules to unsure verified ROMs are used as it can help reduce bug reports etc.

**Comment by barbudreadmon** [comment]
Hmm that's interesting, so it's not a corrupted bios, it's a custom bios.

What's the purpose exactly ? Is there any custom feature you can achieve with that ? How do you build a custom unibios ?

Depending on your answers, i'll try to find a workaround to use custom unibioses when i get some free time.

Anyway i can provide you with a way to create your custom libretro-fbalpha core supporting your custom bios : 
- open src/burner/libretro.libretro.cpp
- search for the line with your bios (should be around line 203)
- replace the crc32 with the crc32 of your custom bios
- compile your custom core

**Comment by Razoola** [comment]
Every unibios has a unique crc32 given every unibios has a unique serial number embedded. There are not custom features.

I will pass the information onto the person though about compiling, I am sure though he does not have the knowledge to compile his own. He will have use the MAME based emulators I guess as this is not an issue present there.

**Comment by twinaphex** [comment]
Hi Razoola, I couldn't help but notice your name. You are the one from Cps2Shock? If so, nice to see you.

**Comment by Razoola** [comment]
Yep, thats me, the maker of the unibios and from cps2shock.

**Comment by AkimanBengus** [comment]
Nice to see you too :-)

**Comment by barbudreadmon** [comment]
Ok, i suppose i could add a core option to disable crc32 check, and use it in find_bios_info function to disable the check, i'll try to work on this in the next few days. That way we keep crc check for safety, except if we want to disable it on purpose in core option.

**Comment by AkimanBengus** [comment]
Ok, but the find_bios_info already look for the filename OR the crc.
For me this is the use of the find_rom_by_crc method that must be conditioned with the core option and use instead the find_rom_by_name

**Comment by barbudreadmon** [comment]
You are right.

**Comment by Razoola** [comment]
Thankyou for considering this.

My personal opinion is, not a new option to totally disabling the crc check method. I don't know if this is helpfull but the way MAME got around this issue in the past (not sure if it is still true today) was to assign a crc of 0x00000000 in the source code to ROMs that were known to be suspect dumps etc. Maybe something like that can be done in the libretro.cpp end of things. In effect add a crc32 of 0x00000000 to the latest 'uni-bios_3_2.rom' in libretro.cpp, Then have find bios except any crc for a file if the expected result is 0x0 providing the filename matched.

**Comment by barbudreadmon** [comment]
I added a fallback to load by name when we can't find crc, can't be sure it works since i don't have an unibios with a custom crc32. Let me know. d686a62b13e62c1e8e58056ec878629d81de75f0

**Comment by Razoola** [comment]
Many thanks for trying to address this barbudreadmon. I'm away from home for a short time and will not have a chance to test it right away You could simply take the free v3.2 unibios currently accepted and change address 0x80 from 0xFFFF to 0xFEFF. This will change the crc32 but still allow the bios to pass its internal crccheck. If you still see v3.2 loading after you know your souce addition works.

**Comment by Razoola** [comment]
I have had a chance to give it a go after compiling (mingw) and changing a byte in the unibios v3.2 ROM like i suggested above. Unfortunately behavior is still the same, black screen in DIPSWITCH mode and reverting to unibiod v3.1 in UNIBIOS mode.

**Comment by AkimanBengus** [comment]
Hey @Razoola, @barbudreadmon 

Barbudreadmon , I did a very small fix at your code to be able to load rom with wrong crc but with good name.
Now it's possible to load an hacked version of the Universe Bios ;-)

**Comment by Razoola** [comment]
Has the source been updated so I can test/try?

**Comment by AkimanBengus** [comment]
My fork is up to date and I made a pull request to the main branch.
Just wait for an admin to commit the request or test directly my fork:
https://github.com/AkimanBengus/fbalpha

I tested like you told and it works because I had a warning message at the beginning that told there is something wrong and when I pushed the 'A' button, the Universe Bios 3.2 started ;-)

**Comment by barbudreadmon** [comment]
Done

**Comment by Razoola** [comment]
I gave it a go and it looks to work as expected now. Nice one.

**Comment by barbudreadmon** [comment]
I close
