### ISSUE TITLE
carnival - Game resets if pressed start

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#97]
title, same bug might exist in some Vic Dual titles.

**Comment by dinkc64** [comment]
Hi arnoldsecret,
vicdual driver (written by a friend) was never finished, I will ask if he wants to finish it.

**Comment by dinkc64** [comment]
I fixed carnival to work, now I am working on adding sound to the game.  I probably wont work on any vicdual games besides Carnival - because it's a classic and this system is very difficult to work with :(

**Comment by dinkc64** [comment]
I didn't think I'd get this far tonight, but Carnival now has complete sound and works good :)
Make sure you get the sample pack from Twisty's samples (google it) under Current Samples.
Thanks for the bug report!
best regards,
- dink
