### ISSUE TITLE
headonb needs headon parent

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/fbalpha#99]
@dinkc64 i noticed you marked headon as a debug driver in the commit to fix carnival, however headon is required by headonb, which is marked as working (and do seem to work apart from sound ?). However headonb doesn't seem to need any file from its parent, so i'm not sure what's the best course of action here (make headon available as non-debug again or replace headonb parent by NULL ?).

With current code, headonb is crashing for me (the 2 solutions above fix it), and somehow its dat entry get messed up (that's actually why i checked the game : it somehow ended up as a clone of zzyzzyxx in https://github.com/libretro/fbalpha/commit/7a7be41829519cbe6cdc3799eee6e2344cb3c2a3)

**Comment by dinkc64** [comment]
sorry about that! get git
